// Package patchstruct applies a patch.Patch to a hand-written Go struct.
//
// It is for plain domain types — configuration structs, DTOs. A struct
// generated by protoc is already a proto.Message, which patchproto applies to
// directly through protoreflect; under the opaque API its fields are
// unexported and reflect cannot reach them at all.
//
// Go's static types answer more of the format's questions than schema-less
// JSON can. A struct is not a map, an int32 is not an int64, a map's key type
// is declared, and a name absent from a struct type genuinely names nothing.
// So this engine enforces the arm tables, the map-key types, and the
// declared/undeclared distinction, where patchjson has to let them go.
//
// What a hand-written struct still cannot supply, all REFUSED rather than
// approximated:
//
//	Field.number    a Go struct has no field numbers
//	Value.e         a Go type carries no set of declared enum values
//	arrays          [N]T cannot change length
//	interface, chan, func, complex, **T
//
// And two the format asks for that cannot be checked here:
//
//	Patch.message_type    a Go type name is not a protobuf name; pass
//	                      ExpectType to supply the name it must match
//	oneof occupancy       Go has no oneof, so insert's sibling rule is vacuous
//
// Addressing follows protobuf's split: Field.name is the Go field name and
// Field.json_name is the `json` tag. A Field that pins both requires them to
// describe the same field. Embedded fields are not flattened — they are
// addressed by their type name, like any other field.
package patchstruct

import (
	"reflect"
	"sort"

	"github.com/lesomnus/protobuf-patch/patch"
	"github.com/lesomnus/protobuf-patch/patchpb"
)

// Option configures Apply.
type Option func(*options)

type options struct {
	expect string
	limits patch.Limits
}

// WithLimits bounds how deep into a document this call will recurse.
//
// The schema requires a bound and leaves the number to the implementation;
// patch.DefaultLimits is what applies when this option is absent. Raise it for
// a producer that legitimately sends deep literals, lower it to be stricter
// with documents from somewhere you do not control.
func WithLimits(l patch.Limits) Option {
	return func(o *options) { o.limits = l }
}

// ExpectType supplies the name a Patch's message_type must match.
//
// A Go type name is not a protobuf message name, so without this there is
// nothing to compare against and the field goes unchecked. The check also only
// applies when the document declares a type: a Patch with no message_type is
// type-agnostic by construction and passes.
func ExpectType(name string) Option {
	return func(o *options) { o.expect = name }
}

// Apply returns v with p applied to it.
//
// It is ATOMIC: p is applied to a copy which is returned only on success, so a
// failure leaves v untouched. The copy is deep through everything this engine
// can address — exported struct fields, maps, slices, pointers. Anything
// reachable only through an unexported field is shared with the original,
// which is safe because it is also unreachable to a Patch.
func Apply[T any](v T, p *patchpb.Patch, opts ...Option) (T, error) {
	var zero T

	var o options
	for _, opt := range opts {
		opt(&o)
	}
	if err := patch.ValidateWith(p, o.limits); err != nil {
		return zero, err
	}
	if o.expect != "" && p.HasMessageType() && p.GetMessageType() != o.expect {
		return zero, patch.Errf(patch.CodeMessageTypeMismatch, "message_type",
			"the document was authored against %s, not %s", p.GetMessageType(), o.expect)
	}

	draft := reflect.New(reflect.TypeOf(v)).Elem()
	draft.Set(deepCopy(reflect.ValueOf(v)))

	c, err := rootCont(draft)
	if err != nil {
		return zero, err
	}
	if err := applyDelta(c, p.GetDelta(), patch.At("delta")); err != nil {
		return zero, err
	}
	return draft.Interface().(T), nil
}

func rootCont(v reflect.Value) (cont, error) {
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return cont{}, patch.Errf(patch.CodeMissingField, "", "nil target")
		}
		v = v.Elem()
	}
	switch v.Kind() {
	case reflect.Struct, reflect.Map:
		return cont{v: v}, nil
	case reflect.Slice:
		if v.Type() != byteSlice {
			return cont{v: v}, nil
		}
	}
	return cont{}, patch.Errf(patch.CodeNotAContainer, "",
		"%s is not a container; a Patch addresses a struct, map, or slice", v.Type())
}

// deepCopy copies everything a Patch could reach.
func deepCopy(v reflect.Value) reflect.Value {
	switch v.Kind() {
	case reflect.Ptr:
		if v.IsNil() {
			return v
		}
		out := reflect.New(v.Type().Elem())
		out.Elem().Set(deepCopy(v.Elem()))
		return out

	case reflect.Slice:
		if v.IsNil() {
			return v
		}
		out := reflect.MakeSlice(v.Type(), v.Len(), v.Len())
		for i := range v.Len() {
			out.Index(i).Set(deepCopy(v.Index(i)))
		}
		return out

	case reflect.Map:
		if v.IsNil() {
			return v
		}
		out := reflect.MakeMapWithSize(v.Type(), v.Len())
		iter := v.MapRange()
		for iter.Next() {
			out.SetMapIndex(iter.Key(), deepCopy(iter.Value()))
		}
		return out

	case reflect.Struct:
		out := reflect.New(v.Type()).Elem()
		out.Set(v) // carries the unexported fields across wholesale
		for i := range v.NumField() {
			if v.Type().Field(i).IsExported() {
				out.Field(i).Set(deepCopy(v.Field(i)))
			}
		}
		return out
	}
	return v
}

func applyDelta(c cont, d *patchpb.Delta, at patch.At) error {
	for i, e := range d.GetEntries() {
		if err := applyEntry(c, e, at.Index("entries", i)); err != nil {
			return err
		}
	}
	return nil
}

func applyEntry(base cont, e *patchpb.Entry, at patch.At) error {
	c, err := navigate(base, e.GetPath(), at.Sub("path"))
	if err != nil {
		return err
	}

	if e.WhichScope() == patchpb.Entry_Container_case {
		return applyToContainer(c, e, at)
	}

	locs, err := expand(c, e.GetTargets(), e, at.Sub("targets"))
	if err != nil {
		return err
	}
	if e.WhichKind() == patchpb.Entry_Test_case && len(locs) == 0 {
		return patch.Errf(patch.CodeTestVacuous, at,
			"the selectors named no location, so the assertion says nothing")
	}
	if len(locs) == 0 {
		return nil
	}
	return applyToTargets(base, c, locs, e, at)
}

func applyToTargets(base, c cont, locs []loc, e *patchpb.Entry, at patch.At) error {
	switch e.WhichKind() {
	case patchpb.Entry_Remove_case:
		return removeAt(c, locs)
	case patchpb.Entry_Test_case:
		return testAt(c, locs, e.GetTest(), at.Sub("test"))
	case patchpb.Entry_Insert_case:
		return insertAt(c, locs, e.GetInsert().GetValue(), at.Sub("insert").Sub("value"))
	case patchpb.Entry_Assign_case:
		return assignAt(c, locs, e.GetAssign().GetValue(), at.Sub("assign").Sub("value"))
	case patchpb.Entry_Move_case:
		return relocate(base, c, locs, e.GetMove().GetFrom(), true, at.Sub("move"))
	case patchpb.Entry_Copy_case:
		return relocate(base, c, locs, e.GetCopy().GetFrom(), false, at.Sub("copy"))
	case patchpb.Entry_Nest_case:
		return nestAt(c, locs, e.GetNest().GetDelta(), at.Sub("nest").Sub("delta"))
	}
	return nil
}

// ------------------------------------------------------------ remove

func removeAt(c cont, locs []loc) error {
	switch c.kind() {
	case reflect.Struct:
		for _, l := range locs {
			clearValue(c.v.FieldByIndex(l.field.Index))
		}
	case reflect.Map:
		for _, l := range locs {
			c.v.SetMapIndex(l.key, reflect.Value{})
		}
	default:
		idxs := make([]int, 0, len(locs))
		for _, l := range locs {
			if !l.appendArm && !l.noSlot {
				idxs = append(idxs, l.idx)
			}
		}
		sort.Sort(sort.Reverse(sort.IntSlice(idxs)))
		s := c.v
		for _, i := range idxs {
			s = reflect.AppendSlice(s.Slice(0, i), s.Slice(i+1, s.Len()))
		}
		c.v.Set(s)
	}
	return nil
}

// ------------------------------------------------------------ test

func testAt(c cont, locs []loc, t *patchpb.Test, at patch.At) error {
	for _, l := range locs {
		ok, got := probe(c, l)
		if t.WhichWant() == patchpb.Test_Exists_case {
			if ok != t.GetExists() {
				return patch.Errf(patch.CodeTestFailed, at, "at %s", describeLoc(c, l))
			}
			continue
		}
		if !ok {
			return patch.Errf(patch.CodeTestFailed, at, "nothing at %s", describeLoc(c, l))
		}
		want, err := convert(t.GetValue(), got.Type(), at.Sub("value"))
		if err != nil {
			return err
		}
		if !equalDeep(got, want) {
			return patch.Errf(patch.CodeTestFailed, at, "at %s", describeLoc(c, l))
		}
	}
	return nil
}

func probe(c cont, l loc) (bool, reflect.Value) {
	switch c.kind() {
	case reflect.Struct:
		if l.noSlot {
			return false, reflect.Value{}
		}
		v := c.v.FieldByIndex(l.field.Index)
		return present(v), v
	case reflect.Map:
		v := c.v.MapIndex(l.key)
		if !v.IsValid() {
			return false, reflect.Value{}
		}
		return true, v
	default:
		if l.noSlot || l.appendArm {
			return false, reflect.Value{}
		}
		return true, c.v.Index(l.idx)
	}
}

// ------------------------------------------------------------ assign, insert

func assignAt(c cont, locs []loc, v *patchpb.Value, at patch.At) error {
	return writeEach(c, locs, v, at, false)
}

func insertAt(c cont, locs []loc, v *patchpb.Value, at patch.At) error {
	if c.kind() == reflect.Slice {
		return spliceInto(c, locs, v, at)
	}
	return writeEach(c, locs, v, at, true)
}

func writeEach(c cont, locs []loc, v *patchpb.Value, at patch.At, onlyAbsent bool) error {
	for _, l := range locs {
		switch c.kind() {
		case reflect.Struct:
			f := c.v.FieldByIndex(l.field.Index)
			if onlyAbsent && present(f) {
				return patch.Errf(patch.CodeOccupied, at, "%s is already set", l.field.Name)
			}
			e, err := convert(v, f.Type(), at)
			if err != nil {
				return err
			}
			f.Set(e)

		case reflect.Map:
			if onlyAbsent && c.v.MapIndex(l.key).IsValid() {
				return patch.Errf(patch.CodeOccupied, at, "the map already has that key")
			}
			e, err := convert(v, c.v.Type().Elem(), at)
			if err != nil {
				return err
			}
			c.v.SetMapIndex(l.key, e)

		default:
			if l.appendArm {
				return patch.Errf(patch.CodeIllegalSelector, at, "assign cannot grow a slice")
			}
			e, err := convert(v, c.v.Type().Elem(), at)
			if err != nil {
				return err
			}
			c.v.Index(l.idx).Set(e)
		}
	}
	return nil
}

// spliceInto inserts before each target index and appends once per append
// selector, rebuilding the slice in one pass. Every index was resolved against
// the pre-entry slice, so inserting at [0, 2] of [a b c] puts a copy before the
// ORIGINAL elements 0 and 2.
func spliceInto(c cont, locs []loc, v *patchpb.Value, at patch.At) error {
	before := map[int]int{}
	appends := 0
	for _, l := range locs {
		if l.appendArm {
			appends++
			continue
		}
		before[l.idx]++
	}

	et := c.v.Type().Elem()
	out := reflect.MakeSlice(c.v.Type(), 0, c.v.Len()+len(locs))
	add := func() error {
		e, err := convert(v, et, at)
		if err != nil {
			return err
		}
		out = reflect.Append(out, e)
		return nil
	}

	for i := range c.v.Len() {
		for range before[i] {
			if err := add(); err != nil {
				return err
			}
		}
		out = reflect.Append(out, c.v.Index(i))
	}
	for range appends {
		if err := add(); err != nil {
			return err
		}
	}
	c.v.Set(out)
	return nil
}

// ------------------------------------------------------------ move, copy

func relocate(base, c cont, locs []loc, from *patchpb.Location, clear bool, at patch.At) error {
	src, srcLoc, err := resolveSource(base, c, from, at.Sub("from"))
	if err != nil {
		return err
	}
	ok, got := probe(src, srcLoc)
	if !ok {
		return patch.Errf(patch.CodeSourceUnresolved, at.Sub("from"),
			"nothing at %s", describeLoc(src, srcLoc))
	}
	held := deepCopy(got)

	sameAsSource := false
	for _, l := range locs {
		if sameLoc(c, src, l, srcLoc) {
			sameAsSource = true
			continue
		}
		dst, err := targetType(c, l)
		if err != nil {
			return err
		}
		if held.Type() != dst {
			return patch.Errf(patch.CodeTypeMismatch, at,
				"the source is %s and the target is %s; there is no conversion", held.Type(), dst)
		}
		if err := writeRaw(c, l, held); err != nil {
			return err
		}
	}
	if clear && !sameAsSource {
		return removeAt(src, []loc{srcLoc})
	}
	return nil
}

func resolveSource(base, c cont, from *patchpb.Location, at patch.At) (cont, loc, error) {
	src := c
	if from.WhichOrigin() == patchpb.Location_Path_case {
		s, err := navigate(base, from.GetPath(), at.Sub("path"))
		if err != nil {
			return cont{}, loc{}, err
		}
		src = s
	}
	l, err := resolveKey(src, from.GetKey(), at.Sub("key"))
	if err != nil {
		return cont{}, loc{}, err
	}
	if l.noSlot || l.emptySlot {
		return cont{}, loc{}, patch.Errf(patch.CodeSourceUnresolved, at.Sub("key"),
			"nothing at that position in %s", src.describe())
	}
	return src, l, nil
}

func targetType(c cont, l loc) (reflect.Type, error) {
	switch c.kind() {
	case reflect.Struct:
		return l.field.Type, nil
	case reflect.Map:
		return c.v.Type().Elem(), nil
	default:
		return c.v.Type().Elem(), nil
	}
}

func sameLoc(a, b cont, x, y loc) bool {
	if a.kind() != b.kind() || a.v.Type() != b.v.Type() {
		return false
	}
	if a.v.CanAddr() && b.v.CanAddr() && a.v.UnsafeAddr() != b.v.UnsafeAddr() {
		return false
	}
	switch a.kind() {
	case reflect.Struct:
		return x.field.Name == y.field.Name
	case reflect.Map:
		return x.key.Interface() == y.key.Interface()
	default:
		return !x.appendArm && !y.appendArm && x.idx == y.idx
	}
}

func writeRaw(c cont, l loc, v reflect.Value) error {
	switch c.kind() {
	case reflect.Struct:
		c.v.FieldByIndex(l.field.Index).Set(v)
	case reflect.Map:
		c.v.SetMapIndex(l.key, v)
	default:
		if l.appendArm {
			c.v.Set(reflect.Append(c.v, v))
			return nil
		}
		c.v.Index(l.idx).Set(v)
	}
	return nil
}

// ------------------------------------------------------------ nest

func nestAt(c cont, locs []loc, d *patchpb.Delta, at patch.At) error {
	for _, l := range locs {
		if c.kind() == reflect.Map {
			// A map entry is not addressable, so nest works on a copy and
			// stores it back.
			held := reflect.New(c.v.Type().Elem()).Elem()
			held.Set(c.v.MapIndex(l.key))
			inner, err := containerOf(held, at)
			if err != nil {
				return err
			}
			if err := applyDelta(inner, d, at); err != nil {
				return err
			}
			c.v.SetMapIndex(l.key, held)
			continue
		}

		var v reflect.Value
		if c.kind() == reflect.Struct {
			v = c.v.FieldByIndex(l.field.Index)
		} else {
			v = c.v.Index(l.idx)
		}
		inner, err := containerOf(v, at)
		if err != nil {
			return err
		}
		if err := applyDelta(inner, d, at); err != nil {
			return err
		}
	}
	return nil
}

func containerOf(v reflect.Value, at patch.At) (cont, error) {
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return cont{}, patch.Errf(patch.CodeNotAContainer, at, "that position is nil")
		}
		v = v.Elem()
	}
	switch v.Kind() {
	case reflect.Struct, reflect.Map:
		return cont{v: v}, nil
	case reflect.Slice:
		if v.Type() != byteSlice {
			return cont{v: v}, nil
		}
	}
	return cont{}, patch.Errf(patch.CodeNotAContainer, at, "%s is not a container", v.Type())
}

// ------------------------------------------------------------ helpers

func describeLoc(c cont, l loc) string {
	switch c.kind() {
	case reflect.Struct:
		if l.noSlot {
			return c.describe()
		}
		return l.field.Name
	case reflect.Map:
		return c.describe() + "[" + toString(l.key) + "]"
	default:
		if l.appendArm {
			return c.describe() + "[-]"
		}
		return c.describe() + "[" + itoa(l.idx) + "]"
	}
}

func toString(v reflect.Value) string {
	if v.Kind() == reflect.String {
		return v.String()
	}
	return v.Type().String()
}

func itoa(i int) string {
	if i == 0 {
		return "0"
	}
	neg := i < 0
	if neg {
		i = -i
	}
	var b []byte
	for i > 0 {
		b = append([]byte{byte('0' + i%10)}, b...)
		i /= 10
	}
	if neg {
		return "-" + string(b)
	}
	return string(b)
}
