// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sample/closed.proto

package sample

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Closed int32

const (
	Closed_CLOSED_UNSPECIFIED Closed = 0
	Closed_CLOSED_LO          Closed = 1
	Closed_CLOSED_HI          Closed = 2
)

// Enum value maps for Closed.
var (
	Closed_name = map[int32]string{
		0: "CLOSED_UNSPECIFIED",
		1: "CLOSED_LO",
		2: "CLOSED_HI",
	}
	Closed_value = map[string]int32{
		"CLOSED_UNSPECIFIED": 0,
		"CLOSED_LO":          1,
		"CLOSED_HI":          2,
	}
)

func (x Closed) Enum() *Closed {
	p := new(Closed)
	*p = x
	return p
}

func (x Closed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Closed) Descriptor() protoreflect.EnumDescriptor {
	return file_sample_closed_proto_enumTypes[0].Descriptor()
}

func (Closed) Type() protoreflect.EnumType {
	return &file_sample_closed_proto_enumTypes[0]
}

func (x Closed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_sample_closed_proto protoreflect.FileDescriptor

const file_sample_closed_proto_rawDesc = "" +
	"\n" +
	"\x13sample/closed.proto\x12\x06sample*>\n" +
	"\x06Closed\x12\x16\n" +
	"\x12CLOSED_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCLOSED_LO\x10\x01\x12\r\n" +
	"\tCLOSED_HI\x10\x02B9Z2github.com/lesomnus/protobuf-patch/internal/sample\x92\x03\x02\x10\x02b\beditionsp\xe8\a"

var file_sample_closed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sample_closed_proto_goTypes = []any{
	(Closed)(0), // 0: sample.Closed
}
var file_sample_closed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sample_closed_proto_init() }
func file_sample_closed_proto_init() {
	if File_sample_closed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sample_closed_proto_rawDesc), len(file_sample_closed_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sample_closed_proto_goTypes,
		DependencyIndexes: file_sample_closed_proto_depIdxs,
		EnumInfos:         file_sample_closed_proto_enumTypes,
	}.Build()
	File_sample_closed_proto = out.File
	file_sample_closed_proto_goTypes = nil
	file_sample_closed_proto_depIdxs = nil
}
