// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sample/ext.proto

package sample

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Extendable struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_S_1         *string                `protobuf:"bytes,1,opt,name=s_1,json=s1"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	extensionFields        protoimpl.ExtensionFields
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Extendable) Reset() {
	*x = Extendable{}
	mi := &file_sample_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extendable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extendable) ProtoMessage() {}

func (x *Extendable) ProtoReflect() protoreflect.Message {
	mi := &file_sample_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Extendable) GetS_1() string {
	if x != nil {
		if x.xxx_hidden_S_1 != nil {
			return *x.xxx_hidden_S_1
		}
		return ""
	}
	return ""
}

func (x *Extendable) SetS_1(v string) {
	x.xxx_hidden_S_1 = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Extendable) HasS_1() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Extendable) ClearS_1() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_S_1 = nil
}

type Extendable_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	S_1 *string
}

func (b0 Extendable_builder) Build() *Extendable {
	m0 := &Extendable{}
	b, x := &b0, m0
	_, _ = b, x
	if b.S_1 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_S_1 = b.S_1
	}
	return m0
}

var file_sample_ext_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*Extendable)(nil),
		ExtensionType: (*string)(nil),
		Field:         100,
		Name:          "sample.ext_s",
		Tag:           "bytes,100,opt,name=ext_s",
		Filename:      "sample/ext.proto",
	},
}

// Extension fields to Extendable.
var (
	// optional string ext_s = 100;
	E_ExtS = &file_sample_ext_proto_extTypes[0]
)

var File_sample_ext_proto protoreflect.FileDescriptor

const file_sample_ext_proto_rawDesc = "" +
	"\n" +
	"\x10sample/ext.proto\x12\x06sample\"$\n" +
	"\n" +
	"Extendable\x12\x0f\n" +
	"\x03s_1\x18\x01 \x01(\tR\x02s1*\x05\bd\x10\xc9\x01:'\n" +
	"\x05ext_s\x12\x12.sample.Extendable\x18d \x01(\tR\x04extSB9Z2github.com/lesomnus/protobuf-patch/internal/sample\x92\x03\x02\b\x01b\beditionsp\xe8\a"

var file_sample_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sample_ext_proto_goTypes = []any{
	(*Extendable)(nil), // 0: sample.Extendable
}
var file_sample_ext_proto_depIdxs = []int32{
	0, // 0: sample.ext_s:extendee -> sample.Extendable
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sample_ext_proto_init() }
func file_sample_ext_proto_init() {
	if File_sample_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sample_ext_proto_rawDesc), len(file_sample_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_sample_ext_proto_goTypes,
		DependencyIndexes: file_sample_ext_proto_depIdxs,
		MessageInfos:      file_sample_ext_proto_msgTypes,
		ExtensionInfos:    file_sample_ext_proto_extTypes,
	}.Build()
	File_sample_ext_proto = out.File
	file_sample_ext_proto_goTypes = nil
	file_sample_ext_proto_depIdxs = nil
}
