// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sample/value.proto

package sample

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Level int32

const (
	Level_LEVEL_UNSPECIFIED Level = 0
	Level_LEVEL_LO          Level = 1
	Level_LEVEL_HI          Level = 2
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_LO",
		2: "LEVEL_HI",
	}
	Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_LO":          1,
		"LEVEL_HI":          2,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_sample_value_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_sample_value_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Value struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_F64_1       float64                `protobuf:"fixed64,101,opt,name=f64_1,json=f641"`
	xxx_hidden_F32_1       float32                `protobuf:"fixed32,102,opt,name=f32_1,json=f321"`
	xxx_hidden_I64_1       int64                  `protobuf:"varint,103,opt,name=i64_1,json=i641"`
	xxx_hidden_U64_1       uint64                 `protobuf:"varint,104,opt,name=u64_1,json=u641"`
	xxx_hidden_I32_1       int32                  `protobuf:"varint,105,opt,name=i32_1,json=i321"`
	xxx_hidden_Ux64_1      uint64                 `protobuf:"fixed64,106,opt,name=ux64_1,json=ux641"`
	xxx_hidden_Ux32_1      uint32                 `protobuf:"fixed32,107,opt,name=ux32_1,json=ux321"`
	xxx_hidden_B_1         bool                   `protobuf:"varint,108,opt,name=b_1,json=b1"`
	xxx_hidden_S_1         string                 `protobuf:"bytes,109,opt,name=s_1,json=s1"`
	xxx_hidden_M_1         *Value                 `protobuf:"bytes,111,opt,name=m_1,json=m1"`
	xxx_hidden_Bs_1        []byte                 `protobuf:"bytes,112,opt,name=bs_1,json=bs1"`
	xxx_hidden_U32_1       uint32                 `protobuf:"varint,113,opt,name=u32_1,json=u321"`
	xxx_hidden_Enum_1      Level                  `protobuf:"varint,114,opt,name=enum_1,json=enum1,enum=sample.Level"`
	xxx_hidden_Sx32_1      int32                  `protobuf:"fixed32,115,opt,name=sx32_1,json=sx321"`
	xxx_hidden_Sx64_1      int64                  `protobuf:"fixed64,116,opt,name=sx64_1,json=sx641"`
	xxx_hidden_Si32_1      int32                  `protobuf:"zigzag32,117,opt,name=si32_1,json=si321"`
	xxx_hidden_Si64_1      int64                  `protobuf:"zigzag64,118,opt,name=si64_1,json=si641"`
	xxx_hidden_F64_2       float64                `protobuf:"fixed64,201,opt,name=f64_2,json=f642"`
	xxx_hidden_F32_2       float32                `protobuf:"fixed32,202,opt,name=f32_2,json=f322"`
	xxx_hidden_I64_2       int64                  `protobuf:"varint,203,opt,name=i64_2,json=i642"`
	xxx_hidden_U64_2       uint64                 `protobuf:"varint,204,opt,name=u64_2,json=u642"`
	xxx_hidden_I32_2       int32                  `protobuf:"varint,205,opt,name=i32_2,json=i322"`
	xxx_hidden_Ux64_2      uint64                 `protobuf:"fixed64,206,opt,name=ux64_2,json=ux642"`
	xxx_hidden_Ux32_2      uint32                 `protobuf:"fixed32,207,opt,name=ux32_2,json=ux322"`
	xxx_hidden_B_2         bool                   `protobuf:"varint,208,opt,name=b_2,json=b2"`
	xxx_hidden_S_2         string                 `protobuf:"bytes,209,opt,name=s_2,json=s2"`
	xxx_hidden_M_2         *Value                 `protobuf:"bytes,211,opt,name=m_2,json=m2"`
	xxx_hidden_Bs_2        []byte                 `protobuf:"bytes,212,opt,name=bs_2,json=bs2"`
	xxx_hidden_U32_2       uint32                 `protobuf:"varint,213,opt,name=u32_2,json=u322"`
	xxx_hidden_Enum_2      Level                  `protobuf:"varint,214,opt,name=enum_2,json=enum2,enum=sample.Level"`
	xxx_hidden_Sx32_2      int32                  `protobuf:"fixed32,215,opt,name=sx32_2,json=sx322"`
	xxx_hidden_Sx64_2      int64                  `protobuf:"fixed64,216,opt,name=sx64_2,json=sx642"`
	xxx_hidden_Si32_2      int32                  `protobuf:"zigzag32,217,opt,name=si32_2,json=si322"`
	xxx_hidden_Si64_2      int64                  `protobuf:"zigzag64,218,opt,name=si64_2,json=si642"`
	xxx_hidden_F64_3       float64                `protobuf:"fixed64,301,opt,name=f64_3,json=f643"`
	xxx_hidden_F32_3       float32                `protobuf:"fixed32,302,opt,name=f32_3,json=f323"`
	xxx_hidden_I64_3       int64                  `protobuf:"varint,303,opt,name=i64_3,json=i643"`
	xxx_hidden_U64_3       uint64                 `protobuf:"varint,304,opt,name=u64_3,json=u643"`
	xxx_hidden_I32_3       int32                  `protobuf:"varint,305,opt,name=i32_3,json=i323"`
	xxx_hidden_Ux64_3      uint64                 `protobuf:"fixed64,306,opt,name=ux64_3,json=ux643"`
	xxx_hidden_Ux32_3      uint32                 `protobuf:"fixed32,307,opt,name=ux32_3,json=ux323"`
	xxx_hidden_B_3         bool                   `protobuf:"varint,308,opt,name=b_3,json=b3"`
	xxx_hidden_S_3         string                 `protobuf:"bytes,309,opt,name=s_3,json=s3"`
	xxx_hidden_M_3         *Value                 `protobuf:"bytes,311,opt,name=m_3,json=m3"`
	xxx_hidden_Bs_3        []byte                 `protobuf:"bytes,312,opt,name=bs_3,json=bs3"`
	xxx_hidden_U32_3       uint32                 `protobuf:"varint,313,opt,name=u32_3,json=u323"`
	xxx_hidden_Enum_3      Level                  `protobuf:"varint,314,opt,name=enum_3,json=enum3,enum=sample.Level"`
	xxx_hidden_Sx32_3      int32                  `protobuf:"fixed32,315,opt,name=sx32_3,json=sx323"`
	xxx_hidden_Sx64_3      int64                  `protobuf:"fixed64,316,opt,name=sx64_3,json=sx643"`
	xxx_hidden_Si32_3      int32                  `protobuf:"zigzag32,317,opt,name=si32_3,json=si323"`
	xxx_hidden_Si64_3      int64                  `protobuf:"zigzag64,318,opt,name=si64_3,json=si643"`
	xxx_hidden_OptF64      float64                `protobuf:"fixed64,401,opt,name=opt_f64,json=optF64"`
	xxx_hidden_OptF32      float32                `protobuf:"fixed32,402,opt,name=opt_f32,json=optF32"`
	xxx_hidden_OptI64      int64                  `protobuf:"varint,403,opt,name=opt_i64,json=optI64"`
	xxx_hidden_OptU64      uint64                 `protobuf:"varint,404,opt,name=opt_u64,json=optU64"`
	xxx_hidden_OptI32      int32                  `protobuf:"varint,405,opt,name=opt_i32,json=optI32"`
	xxx_hidden_OptUx64     uint64                 `protobuf:"fixed64,406,opt,name=opt_ux64,json=optUx64"`
	xxx_hidden_OptUx32     uint32                 `protobuf:"fixed32,407,opt,name=opt_ux32,json=optUx32"`
	xxx_hidden_OptB        bool                   `protobuf:"varint,408,opt,name=opt_b,json=optB"`
	xxx_hidden_OptS        *string                `protobuf:"bytes,409,opt,name=opt_s,json=optS"`
	xxx_hidden_OptM        *Value                 `protobuf:"bytes,411,opt,name=opt_m,json=optM"`
	xxx_hidden_OptBs       []byte                 `protobuf:"bytes,412,opt,name=opt_bs,json=optBs"`
	xxx_hidden_OptU32      uint32                 `protobuf:"varint,413,opt,name=opt_u32,json=optU32"`
	xxx_hidden_OptEnum     Level                  `protobuf:"varint,414,opt,name=opt_enum,json=optEnum,enum=sample.Level"`
	xxx_hidden_OptSx32     int32                  `protobuf:"fixed32,415,opt,name=opt_sx32,json=optSx32"`
	xxx_hidden_OptSx64     int64                  `protobuf:"fixed64,416,opt,name=opt_sx64,json=optSx64"`
	xxx_hidden_OptSi32     int32                  `protobuf:"zigzag32,417,opt,name=opt_si32,json=optSi32"`
	xxx_hidden_OptSi64     int64                  `protobuf:"zigzag64,418,opt,name=opt_si64,json=optSi64"`
	xxx_hidden_RF64_1      []float64              `protobuf:"fixed64,1001,rep,packed,name=r_f64_1,json=rF641"`
	xxx_hidden_RF32_1      []float32              `protobuf:"fixed32,1002,rep,packed,name=r_f32_1,json=rF321"`
	xxx_hidden_RI64_1      []int64                `protobuf:"varint,1003,rep,packed,name=r_i64_1,json=rI641"`
	xxx_hidden_RU64_1      []uint64               `protobuf:"varint,1004,rep,packed,name=r_u64_1,json=rU641"`
	xxx_hidden_RI32_1      []int32                `protobuf:"varint,1005,rep,packed,name=r_i32_1,json=rI321"`
	xxx_hidden_RUx64_1     []uint64               `protobuf:"fixed64,1006,rep,packed,name=r_ux64_1,json=rUx641"`
	xxx_hidden_RUx32_1     []uint32               `protobuf:"fixed32,1007,rep,packed,name=r_ux32_1,json=rUx321"`
	xxx_hidden_RB_1        []bool                 `protobuf:"varint,1008,rep,packed,name=r_b_1,json=rB1"`
	xxx_hidden_RS_1        []string               `protobuf:"bytes,1009,rep,name=r_s_1,json=rS1"`
	xxx_hidden_RM_1        *[]*Value              `protobuf:"bytes,1011,rep,name=r_m_1,json=rM1"`
	xxx_hidden_RBs_1       [][]byte               `protobuf:"bytes,1012,rep,name=r_bs_1,json=rBs1"`
	xxx_hidden_RU32_1      []uint32               `protobuf:"varint,1013,rep,packed,name=r_u32_1,json=rU321"`
	xxx_hidden_REnum_1     []Level                `protobuf:"varint,1014,rep,packed,name=r_enum_1,json=rEnum1,enum=sample.Level"`
	xxx_hidden_RSx32_1     []int32                `protobuf:"fixed32,1015,rep,packed,name=r_sx32_1,json=rSx321"`
	xxx_hidden_RSx64_1     []int64                `protobuf:"fixed64,1016,rep,packed,name=r_sx64_1,json=rSx641"`
	xxx_hidden_RSi32_1     []int32                `protobuf:"zigzag32,1017,rep,packed,name=r_si32_1,json=rSi321"`
	xxx_hidden_RSi64_1     []int64                `protobuf:"zigzag64,1018,rep,packed,name=r_si64_1,json=rSi641"`
	xxx_hidden_MSS         map[string]string      `protobuf:"bytes,10909,rep,name=m_s_s,json=mSS" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MSM         map[string]*Value      `protobuf:"bytes,10911,rep,name=m_s_m,json=mSM" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MI32S       map[int32]string       `protobuf:"bytes,10903,rep,name=m_i32_s,json=mI32S" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MI64S       map[int64]string       `protobuf:"bytes,10905,rep,name=m_i64_s,json=mI64S" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MU32S       map[uint32]string      `protobuf:"bytes,10913,rep,name=m_u32_s,json=mU32S" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MU64S       map[uint64]string      `protobuf:"bytes,10904,rep,name=m_u64_s,json=mU64S" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MSi64S      map[int64]string       `protobuf:"bytes,10918,rep,name=m_si64_s,json=mSi64S" protobuf_key:"zigzag64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MUx32S      map[uint32]string      `protobuf:"bytes,10907,rep,name=m_ux32_s,json=mUx32S" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MBS         map[bool]string        `protobuf:"bytes,10908,rep,name=m_b_s,json=mBS" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Closed_1    Closed                 `protobuf:"varint,119,opt,name=closed_1,json=closed1,enum=sample.Closed"`
	xxx_hidden_Source      isValue_Source         `protobuf_oneof:"source"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [3]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_sample_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_sample_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Value) GetF64_1() float64 {
	if x != nil {
		return x.xxx_hidden_F64_1
	}
	return 0
}

func (x *Value) GetF32_1() float32 {
	if x != nil {
		return x.xxx_hidden_F32_1
	}
	return 0
}

func (x *Value) GetI64_1() int64 {
	if x != nil {
		return x.xxx_hidden_I64_1
	}
	return 0
}

func (x *Value) GetU64_1() uint64 {
	if x != nil {
		return x.xxx_hidden_U64_1
	}
	return 0
}

func (x *Value) GetI32_1() int32 {
	if x != nil {
		return x.xxx_hidden_I32_1
	}
	return 0
}

func (x *Value) GetUx64_1() uint64 {
	if x != nil {
		return x.xxx_hidden_Ux64_1
	}
	return 0
}

func (x *Value) GetUx32_1() uint32 {
	if x != nil {
		return x.xxx_hidden_Ux32_1
	}
	return 0
}

func (x *Value) GetB_1() bool {
	if x != nil {
		return x.xxx_hidden_B_1
	}
	return false
}

func (x *Value) GetS_1() string {
	if x != nil {
		return x.xxx_hidden_S_1
	}
	return ""
}

func (x *Value) GetM_1() *Value {
	if x != nil {
		return x.xxx_hidden_M_1
	}
	return nil
}

func (x *Value) GetBs_1() []byte {
	if x != nil {
		return x.xxx_hidden_Bs_1
	}
	return nil
}

func (x *Value) GetU32_1() uint32 {
	if x != nil {
		return x.xxx_hidden_U32_1
	}
	return 0
}

func (x *Value) GetEnum_1() Level {
	if x != nil {
		return x.xxx_hidden_Enum_1
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *Value) GetSx32_1() int32 {
	if x != nil {
		return x.xxx_hidden_Sx32_1
	}
	return 0
}

func (x *Value) GetSx64_1() int64 {
	if x != nil {
		return x.xxx_hidden_Sx64_1
	}
	return 0
}

func (x *Value) GetSi32_1() int32 {
	if x != nil {
		return x.xxx_hidden_Si32_1
	}
	return 0
}

func (x *Value) GetSi64_1() int64 {
	if x != nil {
		return x.xxx_hidden_Si64_1
	}
	return 0
}

func (x *Value) GetF64_2() float64 {
	if x != nil {
		return x.xxx_hidden_F64_2
	}
	return 0
}

func (x *Value) GetF32_2() float32 {
	if x != nil {
		return x.xxx_hidden_F32_2
	}
	return 0
}

func (x *Value) GetI64_2() int64 {
	if x != nil {
		return x.xxx_hidden_I64_2
	}
	return 0
}

func (x *Value) GetU64_2() uint64 {
	if x != nil {
		return x.xxx_hidden_U64_2
	}
	return 0
}

func (x *Value) GetI32_2() int32 {
	if x != nil {
		return x.xxx_hidden_I32_2
	}
	return 0
}

func (x *Value) GetUx64_2() uint64 {
	if x != nil {
		return x.xxx_hidden_Ux64_2
	}
	return 0
}

func (x *Value) GetUx32_2() uint32 {
	if x != nil {
		return x.xxx_hidden_Ux32_2
	}
	return 0
}

func (x *Value) GetB_2() bool {
	if x != nil {
		return x.xxx_hidden_B_2
	}
	return false
}

func (x *Value) GetS_2() string {
	if x != nil {
		return x.xxx_hidden_S_2
	}
	return ""
}

func (x *Value) GetM_2() *Value {
	if x != nil {
		return x.xxx_hidden_M_2
	}
	return nil
}

func (x *Value) GetBs_2() []byte {
	if x != nil {
		return x.xxx_hidden_Bs_2
	}
	return nil
}

func (x *Value) GetU32_2() uint32 {
	if x != nil {
		return x.xxx_hidden_U32_2
	}
	return 0
}

func (x *Value) GetEnum_2() Level {
	if x != nil {
		return x.xxx_hidden_Enum_2
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *Value) GetSx32_2() int32 {
	if x != nil {
		return x.xxx_hidden_Sx32_2
	}
	return 0
}

func (x *Value) GetSx64_2() int64 {
	if x != nil {
		return x.xxx_hidden_Sx64_2
	}
	return 0
}

func (x *Value) GetSi32_2() int32 {
	if x != nil {
		return x.xxx_hidden_Si32_2
	}
	return 0
}

func (x *Value) GetSi64_2() int64 {
	if x != nil {
		return x.xxx_hidden_Si64_2
	}
	return 0
}

func (x *Value) GetF64_3() float64 {
	if x != nil {
		return x.xxx_hidden_F64_3
	}
	return 0
}

func (x *Value) GetF32_3() float32 {
	if x != nil {
		return x.xxx_hidden_F32_3
	}
	return 0
}

func (x *Value) GetI64_3() int64 {
	if x != nil {
		return x.xxx_hidden_I64_3
	}
	return 0
}

func (x *Value) GetU64_3() uint64 {
	if x != nil {
		return x.xxx_hidden_U64_3
	}
	return 0
}

func (x *Value) GetI32_3() int32 {
	if x != nil {
		return x.xxx_hidden_I32_3
	}
	return 0
}

func (x *Value) GetUx64_3() uint64 {
	if x != nil {
		return x.xxx_hidden_Ux64_3
	}
	return 0
}

func (x *Value) GetUx32_3() uint32 {
	if x != nil {
		return x.xxx_hidden_Ux32_3
	}
	return 0
}

func (x *Value) GetB_3() bool {
	if x != nil {
		return x.xxx_hidden_B_3
	}
	return false
}

func (x *Value) GetS_3() string {
	if x != nil {
		return x.xxx_hidden_S_3
	}
	return ""
}

func (x *Value) GetM_3() *Value {
	if x != nil {
		return x.xxx_hidden_M_3
	}
	return nil
}

func (x *Value) GetBs_3() []byte {
	if x != nil {
		return x.xxx_hidden_Bs_3
	}
	return nil
}

func (x *Value) GetU32_3() uint32 {
	if x != nil {
		return x.xxx_hidden_U32_3
	}
	return 0
}

func (x *Value) GetEnum_3() Level {
	if x != nil {
		return x.xxx_hidden_Enum_3
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *Value) GetSx32_3() int32 {
	if x != nil {
		return x.xxx_hidden_Sx32_3
	}
	return 0
}

func (x *Value) GetSx64_3() int64 {
	if x != nil {
		return x.xxx_hidden_Sx64_3
	}
	return 0
}

func (x *Value) GetSi32_3() int32 {
	if x != nil {
		return x.xxx_hidden_Si32_3
	}
	return 0
}

func (x *Value) GetSi64_3() int64 {
	if x != nil {
		return x.xxx_hidden_Si64_3
	}
	return 0
}

func (x *Value) GetOptF64() float64 {
	if x != nil {
		return x.xxx_hidden_OptF64
	}
	return 0
}

func (x *Value) GetOptF32() float32 {
	if x != nil {
		return x.xxx_hidden_OptF32
	}
	return 0
}

func (x *Value) GetOptI64() int64 {
	if x != nil {
		return x.xxx_hidden_OptI64
	}
	return 0
}

func (x *Value) GetOptU64() uint64 {
	if x != nil {
		return x.xxx_hidden_OptU64
	}
	return 0
}

func (x *Value) GetOptI32() int32 {
	if x != nil {
		return x.xxx_hidden_OptI32
	}
	return 0
}

func (x *Value) GetOptUx64() uint64 {
	if x != nil {
		return x.xxx_hidden_OptUx64
	}
	return 0
}

func (x *Value) GetOptUx32() uint32 {
	if x != nil {
		return x.xxx_hidden_OptUx32
	}
	return 0
}

func (x *Value) GetOptB() bool {
	if x != nil {
		return x.xxx_hidden_OptB
	}
	return false
}

func (x *Value) GetOptS() string {
	if x != nil {
		if x.xxx_hidden_OptS != nil {
			return *x.xxx_hidden_OptS
		}
		return ""
	}
	return ""
}

func (x *Value) GetOptM() *Value {
	if x != nil {
		return x.xxx_hidden_OptM
	}
	return nil
}

func (x *Value) GetOptBs() []byte {
	if x != nil {
		return x.xxx_hidden_OptBs
	}
	return nil
}

func (x *Value) GetOptU32() uint32 {
	if x != nil {
		return x.xxx_hidden_OptU32
	}
	return 0
}

func (x *Value) GetOptEnum() Level {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[1]), 63) {
			return x.xxx_hidden_OptEnum
		}
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *Value) GetOptSx32() int32 {
	if x != nil {
		return x.xxx_hidden_OptSx32
	}
	return 0
}

func (x *Value) GetOptSx64() int64 {
	if x != nil {
		return x.xxx_hidden_OptSx64
	}
	return 0
}

func (x *Value) GetOptSi32() int32 {
	if x != nil {
		return x.xxx_hidden_OptSi32
	}
	return 0
}

func (x *Value) GetOptSi64() int64 {
	if x != nil {
		return x.xxx_hidden_OptSi64
	}
	return 0
}

func (x *Value) GetRF64_1() []float64 {
	if x != nil {
		return x.xxx_hidden_RF64_1
	}
	return nil
}

func (x *Value) GetRF32_1() []float32 {
	if x != nil {
		return x.xxx_hidden_RF32_1
	}
	return nil
}

func (x *Value) GetRI64_1() []int64 {
	if x != nil {
		return x.xxx_hidden_RI64_1
	}
	return nil
}

func (x *Value) GetRU64_1() []uint64 {
	if x != nil {
		return x.xxx_hidden_RU64_1
	}
	return nil
}

func (x *Value) GetRI32_1() []int32 {
	if x != nil {
		return x.xxx_hidden_RI32_1
	}
	return nil
}

func (x *Value) GetRUx64_1() []uint64 {
	if x != nil {
		return x.xxx_hidden_RUx64_1
	}
	return nil
}

func (x *Value) GetRUx32_1() []uint32 {
	if x != nil {
		return x.xxx_hidden_RUx32_1
	}
	return nil
}

func (x *Value) GetRB_1() []bool {
	if x != nil {
		return x.xxx_hidden_RB_1
	}
	return nil
}

func (x *Value) GetRS_1() []string {
	if x != nil {
		return x.xxx_hidden_RS_1
	}
	return nil
}

func (x *Value) GetRM_1() []*Value {
	if x != nil {
		if x.xxx_hidden_RM_1 != nil {
			return *x.xxx_hidden_RM_1
		}
	}
	return nil
}

func (x *Value) GetRBs_1() [][]byte {
	if x != nil {
		return x.xxx_hidden_RBs_1
	}
	return nil
}

func (x *Value) GetRU32_1() []uint32 {
	if x != nil {
		return x.xxx_hidden_RU32_1
	}
	return nil
}

func (x *Value) GetREnum_1() []Level {
	if x != nil {
		return x.xxx_hidden_REnum_1
	}
	return nil
}

func (x *Value) GetRSx32_1() []int32 {
	if x != nil {
		return x.xxx_hidden_RSx32_1
	}
	return nil
}

func (x *Value) GetRSx64_1() []int64 {
	if x != nil {
		return x.xxx_hidden_RSx64_1
	}
	return nil
}

func (x *Value) GetRSi32_1() []int32 {
	if x != nil {
		return x.xxx_hidden_RSi32_1
	}
	return nil
}

func (x *Value) GetRSi64_1() []int64 {
	if x != nil {
		return x.xxx_hidden_RSi64_1
	}
	return nil
}

func (x *Value) GetMSS() map[string]string {
	if x != nil {
		return x.xxx_hidden_MSS
	}
	return nil
}

func (x *Value) GetMSM() map[string]*Value {
	if x != nil {
		return x.xxx_hidden_MSM
	}
	return nil
}

func (x *Value) GetMI32S() map[int32]string {
	if x != nil {
		return x.xxx_hidden_MI32S
	}
	return nil
}

func (x *Value) GetMI64S() map[int64]string {
	if x != nil {
		return x.xxx_hidden_MI64S
	}
	return nil
}

func (x *Value) GetMU32S() map[uint32]string {
	if x != nil {
		return x.xxx_hidden_MU32S
	}
	return nil
}

func (x *Value) GetMU64S() map[uint64]string {
	if x != nil {
		return x.xxx_hidden_MU64S
	}
	return nil
}

func (x *Value) GetMSi64S() map[int64]string {
	if x != nil {
		return x.xxx_hidden_MSi64S
	}
	return nil
}

func (x *Value) GetMUx32S() map[uint32]string {
	if x != nil {
		return x.xxx_hidden_MUx32S
	}
	return nil
}

func (x *Value) GetMBS() map[bool]string {
	if x != nil {
		return x.xxx_hidden_MBS
	}
	return nil
}

func (x *Value) GetClosed_1() Closed {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[2]), 94) {
			return x.xxx_hidden_Closed_1
		}
	}
	return Closed_CLOSED_UNSPECIFIED
}

func (x *Value) GetSrcS() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Source.(*value_SrcS); ok {
			return x.SrcS
		}
	}
	return ""
}

func (x *Value) GetSrcSToo() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Source.(*value_SrcSToo); ok {
			return x.SrcSToo
		}
	}
	return ""
}

func (x *Value) GetSrcI32() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Source.(*value_SrcI32); ok {
			return x.SrcI32
		}
	}
	return 0
}

func (x *Value) GetSrcM() *Value {
	if x != nil {
		if x, ok := x.xxx_hidden_Source.(*value_SrcM); ok {
			return x.SrcM
		}
	}
	return nil
}

func (x *Value) SetF64_1(v float64) {
	x.xxx_hidden_F64_1 = v
}

func (x *Value) SetF32_1(v float32) {
	x.xxx_hidden_F32_1 = v
}

func (x *Value) SetI64_1(v int64) {
	x.xxx_hidden_I64_1 = v
}

func (x *Value) SetU64_1(v uint64) {
	x.xxx_hidden_U64_1 = v
}

func (x *Value) SetI32_1(v int32) {
	x.xxx_hidden_I32_1 = v
}

func (x *Value) SetUx64_1(v uint64) {
	x.xxx_hidden_Ux64_1 = v
}

func (x *Value) SetUx32_1(v uint32) {
	x.xxx_hidden_Ux32_1 = v
}

func (x *Value) SetB_1(v bool) {
	x.xxx_hidden_B_1 = v
}

func (x *Value) SetS_1(v string) {
	x.xxx_hidden_S_1 = v
}

func (x *Value) SetM_1(v *Value) {
	x.xxx_hidden_M_1 = v
}

func (x *Value) SetBs_1(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Bs_1 = v
}

func (x *Value) SetU32_1(v uint32) {
	x.xxx_hidden_U32_1 = v
}

func (x *Value) SetEnum_1(v Level) {
	x.xxx_hidden_Enum_1 = v
}

func (x *Value) SetSx32_1(v int32) {
	x.xxx_hidden_Sx32_1 = v
}

func (x *Value) SetSx64_1(v int64) {
	x.xxx_hidden_Sx64_1 = v
}

func (x *Value) SetSi32_1(v int32) {
	x.xxx_hidden_Si32_1 = v
}

func (x *Value) SetSi64_1(v int64) {
	x.xxx_hidden_Si64_1 = v
}

func (x *Value) SetF64_2(v float64) {
	x.xxx_hidden_F64_2 = v
}

func (x *Value) SetF32_2(v float32) {
	x.xxx_hidden_F32_2 = v
}

func (x *Value) SetI64_2(v int64) {
	x.xxx_hidden_I64_2 = v
}

func (x *Value) SetU64_2(v uint64) {
	x.xxx_hidden_U64_2 = v
}

func (x *Value) SetI32_2(v int32) {
	x.xxx_hidden_I32_2 = v
}

func (x *Value) SetUx64_2(v uint64) {
	x.xxx_hidden_Ux64_2 = v
}

func (x *Value) SetUx32_2(v uint32) {
	x.xxx_hidden_Ux32_2 = v
}

func (x *Value) SetB_2(v bool) {
	x.xxx_hidden_B_2 = v
}

func (x *Value) SetS_2(v string) {
	x.xxx_hidden_S_2 = v
}

func (x *Value) SetM_2(v *Value) {
	x.xxx_hidden_M_2 = v
}

func (x *Value) SetBs_2(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Bs_2 = v
}

func (x *Value) SetU32_2(v uint32) {
	x.xxx_hidden_U32_2 = v
}

func (x *Value) SetEnum_2(v Level) {
	x.xxx_hidden_Enum_2 = v
}

func (x *Value) SetSx32_2(v int32) {
	x.xxx_hidden_Sx32_2 = v
}

func (x *Value) SetSx64_2(v int64) {
	x.xxx_hidden_Sx64_2 = v
}

func (x *Value) SetSi32_2(v int32) {
	x.xxx_hidden_Si32_2 = v
}

func (x *Value) SetSi64_2(v int64) {
	x.xxx_hidden_Si64_2 = v
}

func (x *Value) SetF64_3(v float64) {
	x.xxx_hidden_F64_3 = v
}

func (x *Value) SetF32_3(v float32) {
	x.xxx_hidden_F32_3 = v
}

func (x *Value) SetI64_3(v int64) {
	x.xxx_hidden_I64_3 = v
}

func (x *Value) SetU64_3(v uint64) {
	x.xxx_hidden_U64_3 = v
}

func (x *Value) SetI32_3(v int32) {
	x.xxx_hidden_I32_3 = v
}

func (x *Value) SetUx64_3(v uint64) {
	x.xxx_hidden_Ux64_3 = v
}

func (x *Value) SetUx32_3(v uint32) {
	x.xxx_hidden_Ux32_3 = v
}

func (x *Value) SetB_3(v bool) {
	x.xxx_hidden_B_3 = v
}

func (x *Value) SetS_3(v string) {
	x.xxx_hidden_S_3 = v
}

func (x *Value) SetM_3(v *Value) {
	x.xxx_hidden_M_3 = v
}

func (x *Value) SetBs_3(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Bs_3 = v
}

func (x *Value) SetU32_3(v uint32) {
	x.xxx_hidden_U32_3 = v
}

func (x *Value) SetEnum_3(v Level) {
	x.xxx_hidden_Enum_3 = v
}

func (x *Value) SetSx32_3(v int32) {
	x.xxx_hidden_Sx32_3 = v
}

func (x *Value) SetSx64_3(v int64) {
	x.xxx_hidden_Sx64_3 = v
}

func (x *Value) SetSi32_3(v int32) {
	x.xxx_hidden_Si32_3 = v
}

func (x *Value) SetSi64_3(v int64) {
	x.xxx_hidden_Si64_3 = v
}

func (x *Value) SetOptF64(v float64) {
	x.xxx_hidden_OptF64 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 51, 96)
}

func (x *Value) SetOptF32(v float32) {
	x.xxx_hidden_OptF32 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 52, 96)
}

func (x *Value) SetOptI64(v int64) {
	x.xxx_hidden_OptI64 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 53, 96)
}

func (x *Value) SetOptU64(v uint64) {
	x.xxx_hidden_OptU64 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 54, 96)
}

func (x *Value) SetOptI32(v int32) {
	x.xxx_hidden_OptI32 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 55, 96)
}

func (x *Value) SetOptUx64(v uint64) {
	x.xxx_hidden_OptUx64 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 56, 96)
}

func (x *Value) SetOptUx32(v uint32) {
	x.xxx_hidden_OptUx32 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 57, 96)
}

func (x *Value) SetOptB(v bool) {
	x.xxx_hidden_OptB = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 58, 96)
}

func (x *Value) SetOptS(v string) {
	x.xxx_hidden_OptS = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 59, 96)
}

func (x *Value) SetOptM(v *Value) {
	x.xxx_hidden_OptM = v
}

func (x *Value) SetOptBs(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_OptBs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 61, 96)
}

func (x *Value) SetOptU32(v uint32) {
	x.xxx_hidden_OptU32 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 62, 96)
}

func (x *Value) SetOptEnum(v Level) {
	x.xxx_hidden_OptEnum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 63, 96)
}

func (x *Value) SetOptSx32(v int32) {
	x.xxx_hidden_OptSx32 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[2]), 64, 96)
}

func (x *Value) SetOptSx64(v int64) {
	x.xxx_hidden_OptSx64 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[2]), 65, 96)
}

func (x *Value) SetOptSi32(v int32) {
	x.xxx_hidden_OptSi32 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[2]), 66, 96)
}

func (x *Value) SetOptSi64(v int64) {
	x.xxx_hidden_OptSi64 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[2]), 67, 96)
}

func (x *Value) SetRF64_1(v []float64) {
	x.xxx_hidden_RF64_1 = v
}

func (x *Value) SetRF32_1(v []float32) {
	x.xxx_hidden_RF32_1 = v
}

func (x *Value) SetRI64_1(v []int64) {
	x.xxx_hidden_RI64_1 = v
}

func (x *Value) SetRU64_1(v []uint64) {
	x.xxx_hidden_RU64_1 = v
}

func (x *Value) SetRI32_1(v []int32) {
	x.xxx_hidden_RI32_1 = v
}

func (x *Value) SetRUx64_1(v []uint64) {
	x.xxx_hidden_RUx64_1 = v
}

func (x *Value) SetRUx32_1(v []uint32) {
	x.xxx_hidden_RUx32_1 = v
}

func (x *Value) SetRB_1(v []bool) {
	x.xxx_hidden_RB_1 = v
}

func (x *Value) SetRS_1(v []string) {
	x.xxx_hidden_RS_1 = v
}

func (x *Value) SetRM_1(v []*Value) {
	x.xxx_hidden_RM_1 = &v
}

func (x *Value) SetRBs_1(v [][]byte) {
	x.xxx_hidden_RBs_1 = v
}

func (x *Value) SetRU32_1(v []uint32) {
	x.xxx_hidden_RU32_1 = v
}

func (x *Value) SetREnum_1(v []Level) {
	x.xxx_hidden_REnum_1 = v
}

func (x *Value) SetRSx32_1(v []int32) {
	x.xxx_hidden_RSx32_1 = v
}

func (x *Value) SetRSx64_1(v []int64) {
	x.xxx_hidden_RSx64_1 = v
}

func (x *Value) SetRSi32_1(v []int32) {
	x.xxx_hidden_RSi32_1 = v
}

func (x *Value) SetRSi64_1(v []int64) {
	x.xxx_hidden_RSi64_1 = v
}

func (x *Value) SetMSS(v map[string]string) {
	x.xxx_hidden_MSS = v
}

func (x *Value) SetMSM(v map[string]*Value) {
	x.xxx_hidden_MSM = v
}

func (x *Value) SetMI32S(v map[int32]string) {
	x.xxx_hidden_MI32S = v
}

func (x *Value) SetMI64S(v map[int64]string) {
	x.xxx_hidden_MI64S = v
}

func (x *Value) SetMU32S(v map[uint32]string) {
	x.xxx_hidden_MU32S = v
}

func (x *Value) SetMU64S(v map[uint64]string) {
	x.xxx_hidden_MU64S = v
}

func (x *Value) SetMSi64S(v map[int64]string) {
	x.xxx_hidden_MSi64S = v
}

func (x *Value) SetMUx32S(v map[uint32]string) {
	x.xxx_hidden_MUx32S = v
}

func (x *Value) SetMBS(v map[bool]string) {
	x.xxx_hidden_MBS = v
}

func (x *Value) SetClosed_1(v Closed) {
	x.xxx_hidden_Closed_1 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[2]), 94, 96)
}

func (x *Value) SetSrcS(v string) {
	x.xxx_hidden_Source = &value_SrcS{v}
}

func (x *Value) SetSrcSToo(v string) {
	x.xxx_hidden_Source = &value_SrcSToo{v}
}

func (x *Value) SetSrcI32(v int32) {
	x.xxx_hidden_Source = &value_SrcI32{v}
}

func (x *Value) SetSrcM(v *Value) {
	if v == nil {
		x.xxx_hidden_Source = nil
		return
	}
	x.xxx_hidden_Source = &value_SrcM{v}
}

func (x *Value) HasM_1() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_M_1 != nil
}

func (x *Value) HasM_2() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_M_2 != nil
}

func (x *Value) HasM_3() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_M_3 != nil
}

func (x *Value) HasOptF64() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 51)
}

func (x *Value) HasOptF32() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 52)
}

func (x *Value) HasOptI64() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 53)
}

func (x *Value) HasOptU64() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 54)
}

func (x *Value) HasOptI32() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 55)
}

func (x *Value) HasOptUx64() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 56)
}

func (x *Value) HasOptUx32() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 57)
}

func (x *Value) HasOptB() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 58)
}

func (x *Value) HasOptS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 59)
}

func (x *Value) HasOptM() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OptM != nil
}

func (x *Value) HasOptBs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 61)
}

func (x *Value) HasOptU32() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 62)
}

func (x *Value) HasOptEnum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 63)
}

func (x *Value) HasOptSx32() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[2]), 64)
}

func (x *Value) HasOptSx64() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[2]), 65)
}

func (x *Value) HasOptSi32() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[2]), 66)
}

func (x *Value) HasOptSi64() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[2]), 67)
}

func (x *Value) HasClosed_1() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[2]), 94)
}

func (x *Value) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *Value) HasSrcS() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Source.(*value_SrcS)
	return ok
}

func (x *Value) HasSrcSToo() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Source.(*value_SrcSToo)
	return ok
}

func (x *Value) HasSrcI32() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Source.(*value_SrcI32)
	return ok
}

func (x *Value) HasSrcM() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Source.(*value_SrcM)
	return ok
}

func (x *Value) ClearM_1() {
	x.xxx_hidden_M_1 = nil
}

func (x *Value) ClearM_2() {
	x.xxx_hidden_M_2 = nil
}

func (x *Value) ClearM_3() {
	x.xxx_hidden_M_3 = nil
}

func (x *Value) ClearOptF64() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 51)
	x.xxx_hidden_OptF64 = 0
}

func (x *Value) ClearOptF32() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 52)
	x.xxx_hidden_OptF32 = 0
}

func (x *Value) ClearOptI64() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 53)
	x.xxx_hidden_OptI64 = 0
}

func (x *Value) ClearOptU64() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 54)
	x.xxx_hidden_OptU64 = 0
}

func (x *Value) ClearOptI32() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 55)
	x.xxx_hidden_OptI32 = 0
}

func (x *Value) ClearOptUx64() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 56)
	x.xxx_hidden_OptUx64 = 0
}

func (x *Value) ClearOptUx32() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 57)
	x.xxx_hidden_OptUx32 = 0
}

func (x *Value) ClearOptB() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 58)
	x.xxx_hidden_OptB = false
}

func (x *Value) ClearOptS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 59)
	x.xxx_hidden_OptS = nil
}

func (x *Value) ClearOptM() {
	x.xxx_hidden_OptM = nil
}

func (x *Value) ClearOptBs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 61)
	x.xxx_hidden_OptBs = nil
}

func (x *Value) ClearOptU32() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 62)
	x.xxx_hidden_OptU32 = 0
}

func (x *Value) ClearOptEnum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 63)
	x.xxx_hidden_OptEnum = Level_LEVEL_UNSPECIFIED
}

func (x *Value) ClearOptSx32() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[2]), 64)
	x.xxx_hidden_OptSx32 = 0
}

func (x *Value) ClearOptSx64() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[2]), 65)
	x.xxx_hidden_OptSx64 = 0
}

func (x *Value) ClearOptSi32() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[2]), 66)
	x.xxx_hidden_OptSi32 = 0
}

func (x *Value) ClearOptSi64() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[2]), 67)
	x.xxx_hidden_OptSi64 = 0
}

func (x *Value) ClearClosed_1() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[2]), 94)
	x.xxx_hidden_Closed_1 = Closed_CLOSED_UNSPECIFIED
}

func (x *Value) ClearSource() {
	x.xxx_hidden_Source = nil
}

func (x *Value) ClearSrcS() {
	if _, ok := x.xxx_hidden_Source.(*value_SrcS); ok {
		x.xxx_hidden_Source = nil
	}
}

func (x *Value) ClearSrcSToo() {
	if _, ok := x.xxx_hidden_Source.(*value_SrcSToo); ok {
		x.xxx_hidden_Source = nil
	}
}

func (x *Value) ClearSrcI32() {
	if _, ok := x.xxx_hidden_Source.(*value_SrcI32); ok {
		x.xxx_hidden_Source = nil
	}
}

func (x *Value) ClearSrcM() {
	if _, ok := x.xxx_hidden_Source.(*value_SrcM); ok {
		x.xxx_hidden_Source = nil
	}
}

const Value_Source_not_set_case case_Value_Source = 0
const Value_SrcS_case case_Value_Source = 121
const Value_SrcSToo_case case_Value_Source = 122
const Value_SrcI32_case case_Value_Source = 123
const Value_SrcM_case case_Value_Source = 124

func (x *Value) WhichSource() case_Value_Source {
	if x == nil {
		return Value_Source_not_set_case
	}
	switch x.xxx_hidden_Source.(type) {
	case *value_SrcS:
		return Value_SrcS_case
	case *value_SrcSToo:
		return Value_SrcSToo_case
	case *value_SrcI32:
		return Value_SrcI32_case
	case *value_SrcM:
		return Value_SrcM_case
	default:
		return Value_Source_not_set_case
	}
}

type Value_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	F64_1   float64
	F32_1   float32
	I64_1   int64
	U64_1   uint64
	I32_1   int32
	Ux64_1  uint64
	Ux32_1  uint32
	B_1     bool
	S_1     string
	M_1     *Value
	Bs_1    []byte
	U32_1   uint32
	Enum_1  Level
	Sx32_1  int32
	Sx64_1  int64
	Si32_1  int32
	Si64_1  int64
	F64_2   float64
	F32_2   float32
	I64_2   int64
	U64_2   uint64
	I32_2   int32
	Ux64_2  uint64
	Ux32_2  uint32
	B_2     bool
	S_2     string
	M_2     *Value
	Bs_2    []byte
	U32_2   uint32
	Enum_2  Level
	Sx32_2  int32
	Sx64_2  int64
	Si32_2  int32
	Si64_2  int64
	F64_3   float64
	F32_3   float32
	I64_3   int64
	U64_3   uint64
	I32_3   int32
	Ux64_3  uint64
	Ux32_3  uint32
	B_3     bool
	S_3     string
	M_3     *Value
	Bs_3    []byte
	U32_3   uint32
	Enum_3  Level
	Sx32_3  int32
	Sx64_3  int64
	Si32_3  int32
	Si64_3  int64
	OptF64  *float64
	OptF32  *float32
	OptI64  *int64
	OptU64  *uint64
	OptI32  *int32
	OptUx64 *uint64
	OptUx32 *uint32
	OptB    *bool
	OptS    *string
	OptM    *Value
	OptBs   []byte
	OptU32  *uint32
	OptEnum *Level
	OptSx32 *int32
	OptSx64 *int64
	OptSi32 *int32
	OptSi64 *int64
	RF64_1  []float64
	RF32_1  []float32
	RI64_1  []int64
	RU64_1  []uint64
	RI32_1  []int32
	RUx64_1 []uint64
	RUx32_1 []uint32
	RB_1    []bool
	RS_1    []string
	RM_1    []*Value
	RBs_1   [][]byte
	RU32_1  []uint32
	REnum_1 []Level
	RSx32_1 []int32
	RSx64_1 []int64
	RSi32_1 []int32
	RSi64_1 []int64
	MSS     map[string]string
	MSM     map[string]*Value
	// Every legal protobuf map key type, so that MapKey's arm table and its
	// range checks can be exercised against a real descriptor.
	MI32S  map[int32]string
	MI64S  map[int64]string
	MU32S  map[uint32]string
	MU64S  map[uint64]string
	MSi64S map[int64]string
	MUx32S map[uint32]string
	MBS    map[bool]string
	// A closed enum (declared in closed.proto), so that the rule "a closed enum
	// cannot hold a number it does not declare" has something to be checked
	// against. Editions default to open, which is what Level below is.
	//
	// Explicit presence is required: a field with implicit presence may only use
	// an open enum, since the implicit default has to be representable.
	Closed_1 *Closed
	// A oneof, so that Selector.oneof_member has something to address. Two of
	// the members share a type on purpose: that is the case which makes
	// "assign to the oneof, and let the value pick the member" undecidable, and
	// it is why a oneof is a Selector resolving to the member already set
	// rather than a Key naming the oneof itself.

	// Fields of oneof xxx_hidden_Source:
	SrcS    *string
	SrcSToo *string
	SrcI32  *int32
	SrcM    *Value
	// -- end of xxx_hidden_Source
}

func (b0 Value_builder) Build() *Value {
	m0 := &Value{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_F64_1 = b.F64_1
	x.xxx_hidden_F32_1 = b.F32_1
	x.xxx_hidden_I64_1 = b.I64_1
	x.xxx_hidden_U64_1 = b.U64_1
	x.xxx_hidden_I32_1 = b.I32_1
	x.xxx_hidden_Ux64_1 = b.Ux64_1
	x.xxx_hidden_Ux32_1 = b.Ux32_1
	x.xxx_hidden_B_1 = b.B_1
	x.xxx_hidden_S_1 = b.S_1
	x.xxx_hidden_M_1 = b.M_1
	x.xxx_hidden_Bs_1 = b.Bs_1
	x.xxx_hidden_U32_1 = b.U32_1
	x.xxx_hidden_Enum_1 = b.Enum_1
	x.xxx_hidden_Sx32_1 = b.Sx32_1
	x.xxx_hidden_Sx64_1 = b.Sx64_1
	x.xxx_hidden_Si32_1 = b.Si32_1
	x.xxx_hidden_Si64_1 = b.Si64_1
	x.xxx_hidden_F64_2 = b.F64_2
	x.xxx_hidden_F32_2 = b.F32_2
	x.xxx_hidden_I64_2 = b.I64_2
	x.xxx_hidden_U64_2 = b.U64_2
	x.xxx_hidden_I32_2 = b.I32_2
	x.xxx_hidden_Ux64_2 = b.Ux64_2
	x.xxx_hidden_Ux32_2 = b.Ux32_2
	x.xxx_hidden_B_2 = b.B_2
	x.xxx_hidden_S_2 = b.S_2
	x.xxx_hidden_M_2 = b.M_2
	x.xxx_hidden_Bs_2 = b.Bs_2
	x.xxx_hidden_U32_2 = b.U32_2
	x.xxx_hidden_Enum_2 = b.Enum_2
	x.xxx_hidden_Sx32_2 = b.Sx32_2
	x.xxx_hidden_Sx64_2 = b.Sx64_2
	x.xxx_hidden_Si32_2 = b.Si32_2
	x.xxx_hidden_Si64_2 = b.Si64_2
	x.xxx_hidden_F64_3 = b.F64_3
	x.xxx_hidden_F32_3 = b.F32_3
	x.xxx_hidden_I64_3 = b.I64_3
	x.xxx_hidden_U64_3 = b.U64_3
	x.xxx_hidden_I32_3 = b.I32_3
	x.xxx_hidden_Ux64_3 = b.Ux64_3
	x.xxx_hidden_Ux32_3 = b.Ux32_3
	x.xxx_hidden_B_3 = b.B_3
	x.xxx_hidden_S_3 = b.S_3
	x.xxx_hidden_M_3 = b.M_3
	x.xxx_hidden_Bs_3 = b.Bs_3
	x.xxx_hidden_U32_3 = b.U32_3
	x.xxx_hidden_Enum_3 = b.Enum_3
	x.xxx_hidden_Sx32_3 = b.Sx32_3
	x.xxx_hidden_Sx64_3 = b.Sx64_3
	x.xxx_hidden_Si32_3 = b.Si32_3
	x.xxx_hidden_Si64_3 = b.Si64_3
	if b.OptF64 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 51, 96)
		x.xxx_hidden_OptF64 = *b.OptF64
	}
	if b.OptF32 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 52, 96)
		x.xxx_hidden_OptF32 = *b.OptF32
	}
	if b.OptI64 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 53, 96)
		x.xxx_hidden_OptI64 = *b.OptI64
	}
	if b.OptU64 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 54, 96)
		x.xxx_hidden_OptU64 = *b.OptU64
	}
	if b.OptI32 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 55, 96)
		x.xxx_hidden_OptI32 = *b.OptI32
	}
	if b.OptUx64 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 56, 96)
		x.xxx_hidden_OptUx64 = *b.OptUx64
	}
	if b.OptUx32 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 57, 96)
		x.xxx_hidden_OptUx32 = *b.OptUx32
	}
	if b.OptB != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 58, 96)
		x.xxx_hidden_OptB = *b.OptB
	}
	if b.OptS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 59, 96)
		x.xxx_hidden_OptS = b.OptS
	}
	x.xxx_hidden_OptM = b.OptM
	if b.OptBs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 61, 96)
		x.xxx_hidden_OptBs = b.OptBs
	}
	if b.OptU32 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 62, 96)
		x.xxx_hidden_OptU32 = *b.OptU32
	}
	if b.OptEnum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 63, 96)
		x.xxx_hidden_OptEnum = *b.OptEnum
	}
	if b.OptSx32 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[2]), 64, 96)
		x.xxx_hidden_OptSx32 = *b.OptSx32
	}
	if b.OptSx64 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[2]), 65, 96)
		x.xxx_hidden_OptSx64 = *b.OptSx64
	}
	if b.OptSi32 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[2]), 66, 96)
		x.xxx_hidden_OptSi32 = *b.OptSi32
	}
	if b.OptSi64 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[2]), 67, 96)
		x.xxx_hidden_OptSi64 = *b.OptSi64
	}
	x.xxx_hidden_RF64_1 = b.RF64_1
	x.xxx_hidden_RF32_1 = b.RF32_1
	x.xxx_hidden_RI64_1 = b.RI64_1
	x.xxx_hidden_RU64_1 = b.RU64_1
	x.xxx_hidden_RI32_1 = b.RI32_1
	x.xxx_hidden_RUx64_1 = b.RUx64_1
	x.xxx_hidden_RUx32_1 = b.RUx32_1
	x.xxx_hidden_RB_1 = b.RB_1
	x.xxx_hidden_RS_1 = b.RS_1
	x.xxx_hidden_RM_1 = &b.RM_1
	x.xxx_hidden_RBs_1 = b.RBs_1
	x.xxx_hidden_RU32_1 = b.RU32_1
	x.xxx_hidden_REnum_1 = b.REnum_1
	x.xxx_hidden_RSx32_1 = b.RSx32_1
	x.xxx_hidden_RSx64_1 = b.RSx64_1
	x.xxx_hidden_RSi32_1 = b.RSi32_1
	x.xxx_hidden_RSi64_1 = b.RSi64_1
	x.xxx_hidden_MSS = b.MSS
	x.xxx_hidden_MSM = b.MSM
	x.xxx_hidden_MI32S = b.MI32S
	x.xxx_hidden_MI64S = b.MI64S
	x.xxx_hidden_MU32S = b.MU32S
	x.xxx_hidden_MU64S = b.MU64S
	x.xxx_hidden_MSi64S = b.MSi64S
	x.xxx_hidden_MUx32S = b.MUx32S
	x.xxx_hidden_MBS = b.MBS
	if b.Closed_1 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[2]), 94, 96)
		x.xxx_hidden_Closed_1 = *b.Closed_1
	}
	if b.SrcS != nil {
		x.xxx_hidden_Source = &value_SrcS{*b.SrcS}
	}
	if b.SrcSToo != nil {
		x.xxx_hidden_Source = &value_SrcSToo{*b.SrcSToo}
	}
	if b.SrcI32 != nil {
		x.xxx_hidden_Source = &value_SrcI32{*b.SrcI32}
	}
	if b.SrcM != nil {
		x.xxx_hidden_Source = &value_SrcM{b.SrcM}
	}
	return m0
}

type case_Value_Source protoreflect.FieldNumber

func (x case_Value_Source) String() string {
	md := file_sample_value_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isValue_Source interface {
	isValue_Source()
}

type value_SrcS struct {
	SrcS string `protobuf:"bytes,121,opt,name=src_s,json=srcS,oneof"`
}

type value_SrcSToo struct {
	SrcSToo string `protobuf:"bytes,122,opt,name=src_s_too,json=srcSToo,oneof"`
}

type value_SrcI32 struct {
	SrcI32 int32 `protobuf:"varint,123,opt,name=src_i32,json=srcI32,oneof"`
}

type value_SrcM struct {
	SrcM *Value `protobuf:"bytes,124,opt,name=src_m,json=srcM,oneof"`
}

func (*value_SrcS) isValue_Source() {}

func (*value_SrcSToo) isValue_Source() {}

func (*value_SrcI32) isValue_Source() {}

func (*value_SrcM) isValue_Source() {}

var File_sample_value_proto protoreflect.FileDescriptor

const file_sample_value_proto_rawDesc = "" +
	"\n" +
	"\x12sample/value.proto\x12\x06sample\x1a\x13sample/closed.proto\"\xce\x1a\n" +
	"\x05Value\x12\x13\n" +
	"\x05f64_1\x18e \x01(\x01R\x04f641\x12\x13\n" +
	"\x05f32_1\x18f \x01(\x02R\x04f321\x12\x13\n" +
	"\x05i64_1\x18g \x01(\x03R\x04i641\x12\x13\n" +
	"\x05u64_1\x18h \x01(\x04R\x04u641\x12\x13\n" +
	"\x05i32_1\x18i \x01(\x05R\x04i321\x12\x15\n" +
	"\x06ux64_1\x18j \x01(\x06R\x05ux641\x12\x15\n" +
	"\x06ux32_1\x18k \x01(\aR\x05ux321\x12\x0f\n" +
	"\x03b_1\x18l \x01(\bR\x02b1\x12\x0f\n" +
	"\x03s_1\x18m \x01(\tR\x02s1\x12\x1e\n" +
	"\x03m_1\x18o \x01(\v2\r.sample.ValueR\x02m1\x12\x11\n" +
	"\x04bs_1\x18p \x01(\fR\x03bs1\x12\x13\n" +
	"\x05u32_1\x18q \x01(\rR\x04u321\x12$\n" +
	"\x06enum_1\x18r \x01(\x0e2\r.sample.LevelR\x05enum1\x12\x15\n" +
	"\x06sx32_1\x18s \x01(\x0fR\x05sx321\x12\x15\n" +
	"\x06sx64_1\x18t \x01(\x10R\x05sx641\x12\x15\n" +
	"\x06si32_1\x18u \x01(\x11R\x05si321\x12\x15\n" +
	"\x06si64_1\x18v \x01(\x12R\x05si641\x12\x14\n" +
	"\x05f64_2\x18\xc9\x01 \x01(\x01R\x04f642\x12\x14\n" +
	"\x05f32_2\x18\xca\x01 \x01(\x02R\x04f322\x12\x14\n" +
	"\x05i64_2\x18\xcb\x01 \x01(\x03R\x04i642\x12\x14\n" +
	"\x05u64_2\x18\xcc\x01 \x01(\x04R\x04u642\x12\x14\n" +
	"\x05i32_2\x18\xcd\x01 \x01(\x05R\x04i322\x12\x16\n" +
	"\x06ux64_2\x18\xce\x01 \x01(\x06R\x05ux642\x12\x16\n" +
	"\x06ux32_2\x18\xcf\x01 \x01(\aR\x05ux322\x12\x10\n" +
	"\x03b_2\x18\xd0\x01 \x01(\bR\x02b2\x12\x10\n" +
	"\x03s_2\x18\xd1\x01 \x01(\tR\x02s2\x12\x1f\n" +
	"\x03m_2\x18\xd3\x01 \x01(\v2\r.sample.ValueR\x02m2\x12\x12\n" +
	"\x04bs_2\x18\xd4\x01 \x01(\fR\x03bs2\x12\x14\n" +
	"\x05u32_2\x18\xd5\x01 \x01(\rR\x04u322\x12%\n" +
	"\x06enum_2\x18\xd6\x01 \x01(\x0e2\r.sample.LevelR\x05enum2\x12\x16\n" +
	"\x06sx32_2\x18\xd7\x01 \x01(\x0fR\x05sx322\x12\x16\n" +
	"\x06sx64_2\x18\xd8\x01 \x01(\x10R\x05sx642\x12\x16\n" +
	"\x06si32_2\x18\xd9\x01 \x01(\x11R\x05si322\x12\x16\n" +
	"\x06si64_2\x18\xda\x01 \x01(\x12R\x05si642\x12\x14\n" +
	"\x05f64_3\x18\xad\x02 \x01(\x01R\x04f643\x12\x14\n" +
	"\x05f32_3\x18\xae\x02 \x01(\x02R\x04f323\x12\x14\n" +
	"\x05i64_3\x18\xaf\x02 \x01(\x03R\x04i643\x12\x14\n" +
	"\x05u64_3\x18\xb0\x02 \x01(\x04R\x04u643\x12\x14\n" +
	"\x05i32_3\x18\xb1\x02 \x01(\x05R\x04i323\x12\x16\n" +
	"\x06ux64_3\x18\xb2\x02 \x01(\x06R\x05ux643\x12\x16\n" +
	"\x06ux32_3\x18\xb3\x02 \x01(\aR\x05ux323\x12\x10\n" +
	"\x03b_3\x18\xb4\x02 \x01(\bR\x02b3\x12\x10\n" +
	"\x03s_3\x18\xb5\x02 \x01(\tR\x02s3\x12\x1f\n" +
	"\x03m_3\x18\xb7\x02 \x01(\v2\r.sample.ValueR\x02m3\x12\x12\n" +
	"\x04bs_3\x18\xb8\x02 \x01(\fR\x03bs3\x12\x14\n" +
	"\x05u32_3\x18\xb9\x02 \x01(\rR\x04u323\x12%\n" +
	"\x06enum_3\x18\xba\x02 \x01(\x0e2\r.sample.LevelR\x05enum3\x12\x16\n" +
	"\x06sx32_3\x18\xbb\x02 \x01(\x0fR\x05sx323\x12\x16\n" +
	"\x06sx64_3\x18\xbc\x02 \x01(\x10R\x05sx643\x12\x16\n" +
	"\x06si32_3\x18\xbd\x02 \x01(\x11R\x05si323\x12\x16\n" +
	"\x06si64_3\x18\xbe\x02 \x01(\x12R\x05si643\x12\x1f\n" +
	"\aopt_f64\x18\x91\x03 \x01(\x01B\x05\xaa\x01\x02\b\x01R\x06optF64\x12\x1f\n" +
	"\aopt_f32\x18\x92\x03 \x01(\x02B\x05\xaa\x01\x02\b\x01R\x06optF32\x12\x1f\n" +
	"\aopt_i64\x18\x93\x03 \x01(\x03B\x05\xaa\x01\x02\b\x01R\x06optI64\x12\x1f\n" +
	"\aopt_u64\x18\x94\x03 \x01(\x04B\x05\xaa\x01\x02\b\x01R\x06optU64\x12\x1f\n" +
	"\aopt_i32\x18\x95\x03 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x06optI32\x12!\n" +
	"\bopt_ux64\x18\x96\x03 \x01(\x06B\x05\xaa\x01\x02\b\x01R\aoptUx64\x12!\n" +
	"\bopt_ux32\x18\x97\x03 \x01(\aB\x05\xaa\x01\x02\b\x01R\aoptUx32\x12\x1b\n" +
	"\x05opt_b\x18\x98\x03 \x01(\bB\x05\xaa\x01\x02\b\x01R\x04optB\x12\x1b\n" +
	"\x05opt_s\x18\x99\x03 \x01(\tB\x05\xaa\x01\x02\b\x01R\x04optS\x12*\n" +
	"\x05opt_m\x18\x9b\x03 \x01(\v2\r.sample.ValueB\x05\xaa\x01\x02\b\x01R\x04optM\x12\x1d\n" +
	"\x06opt_bs\x18\x9c\x03 \x01(\fB\x05\xaa\x01\x02\b\x01R\x05optBs\x12\x1f\n" +
	"\aopt_u32\x18\x9d\x03 \x01(\rB\x05\xaa\x01\x02\b\x01R\x06optU32\x120\n" +
	"\bopt_enum\x18\x9e\x03 \x01(\x0e2\r.sample.LevelB\x05\xaa\x01\x02\b\x01R\aoptEnum\x12!\n" +
	"\bopt_sx32\x18\x9f\x03 \x01(\x0fB\x05\xaa\x01\x02\b\x01R\aoptSx32\x12!\n" +
	"\bopt_sx64\x18\xa0\x03 \x01(\x10B\x05\xaa\x01\x02\b\x01R\aoptSx64\x12!\n" +
	"\bopt_si32\x18\xa1\x03 \x01(\x11B\x05\xaa\x01\x02\b\x01R\aoptSi32\x12!\n" +
	"\bopt_si64\x18\xa2\x03 \x01(\x12B\x05\xaa\x01\x02\b\x01R\aoptSi64\x12\x17\n" +
	"\ar_f64_1\x18\xe9\a \x03(\x01R\x05rF641\x12\x17\n" +
	"\ar_f32_1\x18\xea\a \x03(\x02R\x05rF321\x12\x17\n" +
	"\ar_i64_1\x18\xeb\a \x03(\x03R\x05rI641\x12\x17\n" +
	"\ar_u64_1\x18\xec\a \x03(\x04R\x05rU641\x12\x17\n" +
	"\ar_i32_1\x18\xed\a \x03(\x05R\x05rI321\x12\x19\n" +
	"\br_ux64_1\x18\xee\a \x03(\x06R\x06rUx641\x12\x19\n" +
	"\br_ux32_1\x18\xef\a \x03(\aR\x06rUx321\x12\x13\n" +
	"\x05r_b_1\x18\xf0\a \x03(\bR\x03rB1\x12\x13\n" +
	"\x05r_s_1\x18\xf1\a \x03(\tR\x03rS1\x12\"\n" +
	"\x05r_m_1\x18\xf3\a \x03(\v2\r.sample.ValueR\x03rM1\x12\x15\n" +
	"\x06r_bs_1\x18\xf4\a \x03(\fR\x04rBs1\x12\x17\n" +
	"\ar_u32_1\x18\xf5\a \x03(\rR\x05rU321\x12(\n" +
	"\br_enum_1\x18\xf6\a \x03(\x0e2\r.sample.LevelR\x06rEnum1\x12\x19\n" +
	"\br_sx32_1\x18\xf7\a \x03(\x0fR\x06rSx321\x12\x19\n" +
	"\br_sx64_1\x18\xf8\a \x03(\x10R\x06rSx641\x12\x19\n" +
	"\br_si32_1\x18\xf9\a \x03(\x11R\x06rSi321\x12\x19\n" +
	"\br_si64_1\x18\xfa\a \x03(\x12R\x06rSi641\x12+\n" +
	"\x05m_s_s\x18\x9dU \x03(\v2\x16.sample.Value.MSSEntryR\x03mSS\x12+\n" +
	"\x05m_s_m\x18\x9fU \x03(\v2\x16.sample.Value.MSMEntryR\x03mSM\x121\n" +
	"\am_i32_s\x18\x97U \x03(\v2\x18.sample.Value.MI32SEntryR\x05mI32S\x121\n" +
	"\am_i64_s\x18\x99U \x03(\v2\x18.sample.Value.MI64SEntryR\x05mI64S\x121\n" +
	"\am_u32_s\x18\xa1U \x03(\v2\x18.sample.Value.MU32SEntryR\x05mU32S\x121\n" +
	"\am_u64_s\x18\x98U \x03(\v2\x18.sample.Value.MU64SEntryR\x05mU64S\x124\n" +
	"\bm_si64_s\x18\xa6U \x03(\v2\x19.sample.Value.MSi64SEntryR\x06mSi64S\x124\n" +
	"\bm_ux32_s\x18\x9bU \x03(\v2\x19.sample.Value.MUx32SEntryR\x06mUx32S\x12+\n" +
	"\x05m_b_s\x18\x9cU \x03(\v2\x16.sample.Value.MBSEntryR\x03mBS\x120\n" +
	"\bclosed_1\x18w \x01(\x0e2\x0e.sample.ClosedB\x05\xaa\x01\x02\b\x01R\aclosed1\x12\x15\n" +
	"\x05src_s\x18y \x01(\tH\x00R\x04srcS\x12\x1c\n" +
	"\tsrc_s_too\x18z \x01(\tH\x00R\asrcSToo\x12\x19\n" +
	"\asrc_i32\x18{ \x01(\x05H\x00R\x06srcI32\x12$\n" +
	"\x05src_m\x18| \x01(\v2\r.sample.ValueH\x00R\x04srcM\x1a6\n" +
	"\bMSSEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\bMSMEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.sample.ValueR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"MI32SEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"MI64SEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"MU32SEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"MU64SEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vMSi64SEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x12R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vMUx32SEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\aR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bMBSEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06source*:\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bLEVEL_LO\x10\x01\x12\f\n" +
	"\bLEVEL_HI\x10\x02B9Z2github.com/lesomnus/protobuf-patch/internal/sample\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_sample_value_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sample_value_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sample_value_proto_goTypes = []any{
	(Level)(0),    // 0: sample.Level
	(*Value)(nil), // 1: sample.Value
	nil,           // 2: sample.Value.MSSEntry
	nil,           // 3: sample.Value.MSMEntry
	nil,           // 4: sample.Value.MI32SEntry
	nil,           // 5: sample.Value.MI64SEntry
	nil,           // 6: sample.Value.MU32SEntry
	nil,           // 7: sample.Value.MU64SEntry
	nil,           // 8: sample.Value.MSi64SEntry
	nil,           // 9: sample.Value.MUx32SEntry
	nil,           // 10: sample.Value.MBSEntry
	(Closed)(0),   // 11: sample.Closed
}
var file_sample_value_proto_depIdxs = []int32{
	1,  // 0: sample.Value.m_1:type_name -> sample.Value
	0,  // 1: sample.Value.enum_1:type_name -> sample.Level
	1,  // 2: sample.Value.m_2:type_name -> sample.Value
	0,  // 3: sample.Value.enum_2:type_name -> sample.Level
	1,  // 4: sample.Value.m_3:type_name -> sample.Value
	0,  // 5: sample.Value.enum_3:type_name -> sample.Level
	1,  // 6: sample.Value.opt_m:type_name -> sample.Value
	0,  // 7: sample.Value.opt_enum:type_name -> sample.Level
	1,  // 8: sample.Value.r_m_1:type_name -> sample.Value
	0,  // 9: sample.Value.r_enum_1:type_name -> sample.Level
	2,  // 10: sample.Value.m_s_s:type_name -> sample.Value.MSSEntry
	3,  // 11: sample.Value.m_s_m:type_name -> sample.Value.MSMEntry
	4,  // 12: sample.Value.m_i32_s:type_name -> sample.Value.MI32SEntry
	5,  // 13: sample.Value.m_i64_s:type_name -> sample.Value.MI64SEntry
	6,  // 14: sample.Value.m_u32_s:type_name -> sample.Value.MU32SEntry
	7,  // 15: sample.Value.m_u64_s:type_name -> sample.Value.MU64SEntry
	8,  // 16: sample.Value.m_si64_s:type_name -> sample.Value.MSi64SEntry
	9,  // 17: sample.Value.m_ux32_s:type_name -> sample.Value.MUx32SEntry
	10, // 18: sample.Value.m_b_s:type_name -> sample.Value.MBSEntry
	11, // 19: sample.Value.closed_1:type_name -> sample.Closed
	1,  // 20: sample.Value.src_m:type_name -> sample.Value
	1,  // 21: sample.Value.MSMEntry.value:type_name -> sample.Value
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_sample_value_proto_init() }
func file_sample_value_proto_init() {
	if File_sample_value_proto != nil {
		return
	}
	file_sample_closed_proto_init()
	file_sample_value_proto_msgTypes[0].OneofWrappers = []any{
		(*value_SrcS)(nil),
		(*value_SrcSToo)(nil),
		(*value_SrcI32)(nil),
		(*value_SrcM)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sample_value_proto_rawDesc), len(file_sample_value_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sample_value_proto_goTypes,
		DependencyIndexes: file_sample_value_proto_depIdxs,
		EnumInfos:         file_sample_value_proto_enumTypes,
		MessageInfos:      file_sample_value_proto_msgTypes,
	}.Build()
	File_sample_value_proto = out.File
	file_sample_value_proto_goTypes = nil
	file_sample_value_proto_depIdxs = nil
}
