// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: patch/patch.proto

package patchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OnAbsentPath says what to do when `Entry.path` reaches a container that does
// not exist.
type OnAbsentPath int32

const (
	// An absent container aborts the Patch. As with `OnMissing`, this is the
	// ONLY encoding of "fail": the safe behavior is the zero value and there is
	// no second way to spell it.
	OnAbsentPath_ON_ABSENT_PATH_UNSPECIFIED OnAbsentPath = 0
	// Create what is missing, and ONLY what is missing.
	//
	//   - An unset singular message field is set to an empty message.
	//   - A map key with no entry, whose value type is a message, gains an empty
	//     entry.
	//   - Anything already there is left exactly as it is. This is not `assign`
	//     of a nested literal, which replaces the container and drops whatever
	//     the document did not name.
	//
	// A list index outside [0, len) is still an ERROR. It cannot be created:
	// growing a list shifts the indices of everything after it, and `insert`
	// with `Selector.append` is what grows a list. So is a field the message
	// does not declare, and so is a segment naming a scalar — in both cases
	// there is nothing that could be created.
	OnAbsentPath_ON_ABSENT_PATH_CREATE OnAbsentPath = 1
)

// Enum value maps for OnAbsentPath.
var (
	OnAbsentPath_name = map[int32]string{
		0: "ON_ABSENT_PATH_UNSPECIFIED",
		1: "ON_ABSENT_PATH_CREATE",
	}
	OnAbsentPath_value = map[string]int32{
		"ON_ABSENT_PATH_UNSPECIFIED": 0,
		"ON_ABSENT_PATH_CREATE":      1,
	}
)

func (x OnAbsentPath) Enum() *OnAbsentPath {
	p := new(OnAbsentPath)
	*p = x
	return p
}

func (x OnAbsentPath) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnAbsentPath) Descriptor() protoreflect.EnumDescriptor {
	return file_patch_patch_proto_enumTypes[0].Descriptor()
}

func (OnAbsentPath) Type() protoreflect.EnumType {
	return &file_patch_patch_proto_enumTypes[0]
}

func (x OnAbsentPath) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type OnMissing int32

const (
	// A missing target aborts the Patch. This is the ONLY encoding of "fail" —
	// there is deliberately no explicit FAIL value, so the meaning has exactly
	// one encoding and the safe behavior is the zero value.
	OnMissing_ON_MISSING_UNSPECIFIED OnMissing = 0
	// A missing target is skipped. The author opted into this on the wire; a
	// reader never chooses it.
	OnMissing_ON_MISSING_SKIP OnMissing = 1
)

// Enum value maps for OnMissing.
var (
	OnMissing_name = map[int32]string{
		0: "ON_MISSING_UNSPECIFIED",
		1: "ON_MISSING_SKIP",
	}
	OnMissing_value = map[string]int32{
		"ON_MISSING_UNSPECIFIED": 0,
		"ON_MISSING_SKIP":        1,
	}
)

func (x OnMissing) Enum() *OnMissing {
	p := new(OnMissing)
	*p = x
	return p
}

func (x OnMissing) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnMissing) Descriptor() protoreflect.EnumDescriptor {
	return file_patch_patch_proto_enumTypes[1].Descriptor()
}

func (OnMissing) Type() protoreflect.EnumType {
	return &file_patch_patch_proto_enumTypes[1]
}

func (x OnMissing) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Patch is a self-identifying patch DOCUMENT: the unit that is stored,
// transmitted, and applied.
//
// A `Delta` on its own is a FRAGMENT — its addressing is relative to whichever
// container it is applied to, so it does not carry enough information to be
// interpreted alone. Only a Patch names its target and its requirements. Store
// and transmit Patches, not bare Deltas.
//
// ============================ FAILURE CONTRACT ============================
//
// Everything below is normative. The governing principle is that an
// implementation must never silently do less than the document asks.
//
// ATOMICITY. A Patch applies entirely or not at all. Full pre-validation is
// NOT sufficient — an entry's legality can depend on state that earlier
// entries produce — so an implementation MUST apply to a private copy and
// publish it only on success. If any entry fails, the target MUST be
// observably unchanged. There is no partial application and no "best effort"
// mode. An applier that mutates a caller-owned message in place cannot honor
// this contract and MUST NOT be offered as the primary interface.
//
// RESOURCE BOUNDS. A Patch nests without limit in two independent places:
// `nest` chains Deltas, and a `Value` literal nests through `m`, `l`, and
// `map`. Both are recursive, so a document of a few tens of kilobytes can
// describe hundreds of thousands of levels, and a reader that follows them
// naively will spend memory and stack far out of proportion to the input.
//
// An implementation MUST bound the nesting depth it will follow, in both
// places, and MUST fail closed when a document exceeds the bound. The bound
// itself is implementation-defined: this schema fixes no number, because the
// right one depends on the reader's stack and on what its producers
// legitimately send.
//
// A consequence, stated here so that it is not a surprise: a document one
// reader accepts, another may refuse. That is the same shape as
// `min_reader_revision`, and it only ever moves toward refusal — never toward
// a reader applying a document it did not fully process.
//
// `Entry.path` and `Targets.selectors` are repeated rather than recursive.
// They are linear in the size of the document and need no such bound.
//
// UNKNOWN FIELDS ON THE TARGET. Fields present on the target's wire form but
// not declared by its descriptor are not addressable by any `Key`, and are not
// part of the container for `remove` or `assign` at container scope: they MUST
// be preserved unchanged. A Patch never discards data it did not name.
//
// FAIL CLOSED. Every one of the following is an ERROR that aborts the whole
// Patch. None may be skipped, defaulted, or treated as a no-op:
//
//   - `message_type` is set and does not name the target message.
//   - `min_reader_revision` exceeds the revision this reader implements.
//   - An unrecognized `oneof` arm anywhere in the document — in `Entry.kind`,
//     `Entry.scope`, `Selector.kind`, `Key.kind`, `MapKey.kind`, `Value.kind`,
//     `Test.want`, or `Location.origin`. A reader that does not understand an
//     operation MUST refuse the document rather than apply the subset it
//     understands.
//   - Any field number this reader does not recognize, at any depth in the
//     document — including inside `Append`, `Container`, `SameContainer`,
//     `Remove`, `Entry`, and `Patch` itself. A reader MUST inspect the
//     unknown-field set of every decoded message and refuse the document; it
//     MUST NOT merely ignore unknown fields. A Patch therefore MUST NOT be
//     carried over a transport that discards them (e.g. ProtoJSON with
//     DiscardUnknown).
//   - An `OnMissing` or `OnAbsentPath` value not declared in this file.
//   - `Entry.on_absent_path` set on a `test`. Creating a container is a
//     mutation, and a `test` must not mutate.
//   - An unset `oneof` where one is required: `Entry.scope`, `Entry.kind`,
//     `Key.kind`, `MapKey.kind`, `Selector.kind`, `Value.kind`, `Test.want`,
//     `Location.origin`.
//   - An unset required field: `FieldValue.key`, `FieldValue.value`,
//     `MapEntry.key`, `MapEntry.value`, `Location.key`, `Patch.delta`.
//     (`message_type` is NOT among them — see its own comment.)
//   - `Targets.selectors` is empty, or `Delta.entries` is empty. (Address a
//     container explicitly with `Entry.container` — a producer that computed
//     zero targets has a bug, and must not silently be handed the most
//     destructive operation available.)
//   - Two selectors in one entry that resolve to the same location.
//   - A `Field` with no identifier set, or whose set identifiers disagree.
//   - A `Field.number` in an extension range of the message it is resolved
//     against. Extensions are not addressable and MUST NOT be reported as
//     absent (see `Field`).
//   - A selector, key, or value arm that is not legal for the container or
//     field it is applied to (see the tables on `Key`, `MapKey`, and `Value`).
//   - A `Selector.oneof_member` against a container that is not a message, or
//     naming a synthetic oneof, or with an empty `name`.
//   - A `Selector.every_entry` against a container that is not a map.
//   - A `MapKey` value outside the declared key type's range.
//   - A `Value.e` that the target's CLOSED enum does not declare.
//   - `Entry.path` that does not reach an existing container: descending into
//     an unset singular message field, or through a `Key` that names no slot
//     or an empty one. `Entry.on_missing` never applies to `Entry.path`;
//     `Entry.on_absent_path` is what governs it, and only for what can be
//     created.
//   - A `test` that does not hold.
//   - A `test` entry whose selectors resolve to zero locations, or whose
//     `on_missing` is set to anything but the default. A `test` must never be
//     able to pass vacuously.
//   - A `move`/`copy` whose `Location` reaches nothing, or whose source and
//     targets differ in kind or in declared type.
//
// The ONLY tolerated failure is a MISSING TARGET (see `Key`), and only in
// `Entry.targets`, only for kinds other than `test`, and only when the author
// opted in on the wire via `Entry.on_missing`. Tolerance is always a recorded
// decision, never a reader's default.
//
// ==========================================================================
type Patch struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MessageType       *string                `protobuf:"bytes,1,opt,name=message_type,json=messageType"`
	xxx_hidden_MinReaderRevision uint32                 `protobuf:"varint,2,opt,name=min_reader_revision,json=minReaderRevision"`
	xxx_hidden_Delta             *Delta                 `protobuf:"bytes,3,opt,name=delta"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Patch) Reset() {
	*x = Patch{}
	mi := &file_patch_patch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patch) ProtoMessage() {}

func (x *Patch) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Patch) GetMessageType() string {
	if x != nil {
		if x.xxx_hidden_MessageType != nil {
			return *x.xxx_hidden_MessageType
		}
		return ""
	}
	return ""
}

func (x *Patch) GetMinReaderRevision() uint32 {
	if x != nil {
		return x.xxx_hidden_MinReaderRevision
	}
	return 0
}

func (x *Patch) GetDelta() *Delta {
	if x != nil {
		return x.xxx_hidden_Delta
	}
	return nil
}

func (x *Patch) SetMessageType(v string) {
	x.xxx_hidden_MessageType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Patch) SetMinReaderRevision(v uint32) {
	x.xxx_hidden_MinReaderRevision = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Patch) SetDelta(v *Delta) {
	x.xxx_hidden_Delta = v
}

func (x *Patch) HasMessageType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Patch) HasMinReaderRevision() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Patch) HasDelta() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Delta != nil
}

func (x *Patch) ClearMessageType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MessageType = nil
}

func (x *Patch) ClearMinReaderRevision() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MinReaderRevision = 0
}

func (x *Patch) ClearDelta() {
	x.xxx_hidden_Delta = nil
}

type Patch_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fully-qualified name of the message this Patch was authored against, e.g.
	// "example.v1.User".
	//
	// OPTIONAL, and its presence is itself the assertion. When it is set an
	// applier MUST reject a Patch whose `message_type` does not match the
	// message it is being applied to. When it is unset the Patch declares itself
	// TYPE-AGNOSTIC and no such check happens.
	//
	// Leaving it unset is a real case, not a shortcut. Resource messages
	// routinely share a prefix of common fields — a name, an etag, labels — and
	// a Patch that only addresses those applies to every one of them. Requiring
	// a type would force either a copy of the document per resource, or
	// rewriting the field before each apply, and rewriting a stored document to
	// make it applicable defeats the point of storing it.
	//
	// What is lost by leaving it unset is only the coarsest of the format's
	// integrity checks. The finer one survives and is per-field: a `Field` that
	// pins a name against a number still refuses a message whose fields moved
	// (see `Field`), and an unrecognized arm is still refused whatever the type.
	//
	// What is gained by setting it is that a stored Patch — which may outlive
	// the schema it was written against — can be validated, logged, and routed
	// without the target descriptor in hand. Set it whenever the Patch really is
	// for one message.
	MessageType *string
	// The lowest revision of this schema a reader must implement in order to
	// apply the document correctly. 0 means "patch.proto as first published".
	//
	// Unrecognized arms and unknown fields are already hard errors, so this
	// exists for the other kind of change: a revision that alters the MEANING of
	// a construct already defined here. Such a revision increments this number,
	// and every producer relying on the new meaning MUST set it.
	//
	// A reader MUST reject a Patch whose value exceeds the revision it
	// implements. A monotone integer is used rather than a feature-string list
	// so that there is no registry to maintain and no way to spell a capability
	// two ways; the cost is that a revision locks out older readers for every
	// document, not only those using the changed construct.
	MinReaderRevision *uint32
	// The operations, applied to the root message. Required; an unset or empty
	// `delta` is an error.
	Delta *Delta
}

func (b0 Patch_builder) Build() *Patch {
	m0 := &Patch{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MessageType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_MessageType = b.MessageType
	}
	if b.MinReaderRevision != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_MinReaderRevision = *b.MinReaderRevision
	}
	x.xxx_hidden_Delta = b.Delta
	return m0
}

// Delta is an ordered sequence of operations applied to ONE container.
//
// Order is significant: entries are applied in sequence, and each observes the
// effects of those before it.
//
// A Delta is context-dependent — a `Key` inside it names a field, an index, or
// a map key depending on the container the Delta is applied to. It is
// therefore a fragment, not a document; see `Patch`.
type Delta struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*Entry              `protobuf:"bytes,1,rep,name=entries"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_patch_patch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Delta) GetEntries() []*Entry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *Delta) SetEntries(v []*Entry) {
	x.xxx_hidden_Entries = &v
}

type Delta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required; an empty Delta is an error. (A no-op document is expressible as
	// a `test` that holds, which says so explicitly.)
	Entries []*Entry
}

func (b0 Delta_builder) Build() *Delta {
	m0 := &Delta{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

// Entry is one operation.
//
// It reads as three parts:
//
//	path   — navigate INTO a container  (optional; empty = this Delta's container)
//	scope  — WHAT in that container     (required: targets, or the container itself)
//	kind   — the operation              (required: exactly one)
//
// ======================= TARGET RESOLUTION =======================
//
// All selectors resolve against the container state as it was BEFORE the entry
// began. `targets` is an unordered SET: the result does not depend on the
// order the selectors appear in, and two selectors resolving to the same
// location are an error. This holds for every kind, including `insert` and
// `move`.
//
// Worked examples on the list [a, b, c]:
//
//	remove, targets [0, 2]                  => [b]
//	insert Z, targets [key 0, key 2]        => [Z, a, b, Z, c]
//	insert Z, targets [append]              => [a, b, c, Z]
//	assign Z, targets [-1]                  => [a, b, Z]
//	remove, targets [-1]                    => [a, b]
//
// Note that -1 means "the last element" for EVERY kind; appending has its own
// selector rather than overloading a negative index.
//
// A MISSING TARGET (see `Key`) is governed by `on_missing`, whatever the kind,
// with one exception in each direction. `test` READS a missing target instead
// of being governed by it, which is what makes `exists = false` satisfiable.
// And an EMPTY SLOT — a map key with no entry — is missing only for `remove`
// and `nest`, which need something already there; the writing kinds fill it,
// which is how a map entry is created at all.
//
// ======================= OPERATION SEMANTICS =====================
//
// Each kind is defined for all four scopes. "container" is the container
// reached by `path`, addressed via `Entry.container`.
//
// remove — delete the target.
//
//	message field  clear the field. For a field without presence, restore the
//	               default.
//	list index     remove the element; the list shrinks.
//	map key        delete the entry. A key with no entry under it is a
//	               missing target (see `Key`), so by default this fails rather
//	               than quietly deleting nothing.
//	container      message: clear every declared field. list: empty it.
//	               map: empty it.
//
// test — assert, and abort the Patch if the assertion fails.
//
//	Never mutates. `on_missing` may not be set on a `test`, and a `test` whose
//	selectors resolve to zero locations is an error, so a test can never pass
//	vacuously.
//
//	EQUALITY, used by `want.value`, is defined as follows. It is the only
//	comparison the format performs, so it is spelled out rather than left to
//	whatever each implementation's language calls equality.
//	  - Kind and declared type must match first: comparing across types is an
//	    error, not an unequal answer.
//	  - Integers, booleans, and strings: equal values.
//	  - `x`: equal byte sequences.
//	  - `e`: equal numbers, in the same enum type.
//	  - `f32`/`f64`: equal IEEE values, EXCEPT that NaN EQUALS NaN. A test
//	    asserts what a document holds, not an arithmetic predicate; under IEEE
//	    inequality a Patch could `assign` a NaN and then be unable to assert
//	    the value it had just written. -0.0 and +0.0 are equal.
//	  - `m`: EXACT, not subset. Every field set on the target must appear in
//	    `fields` with an equal value, and every field in `fields` must be set
//	    on the target. A field absent from `fields` therefore asserts that the
//	    target does not have it set. For a subset assertion, test the fields
//	    individually, or `nest` a Delta of tests.
//	  - `l`: equal lengths, and elementwise equal in order.
//	  - `map`: equal key sets, and equal values under each key.
//	  - UNKNOWN FIELDS ON THE TARGET TAKE NO PART, at any depth. They are not
//	    addressable and are preserved verbatim, so a Value has no way to
//	    mention one; counting them would make every `test` against a message
//	    carrying any fail, with no Value that could ever pass.
//
//	`want.value`   the target exists and equals the value. Kind and declared
//	               type must match exactly; a missing target fails.
//	`want.exists`  true: the target is present. false: it is absent.
//	               message field: presence as protobuf defines it — an
//	               explicit-presence field that is set, or a field without
//	               presence that differs from its default. An undeclared field
//	               is absent.
//	               list index: the index is within [0, len).
//	               map key: the entry exists.
//	               container: true means NON-EMPTY (a message with at least one
//	               field set, a non-empty list, a non-empty map); false means
//	               empty. The container itself always exists — a `path` that
//	               does not reach one is already an error.
//	Examples:      map without key "k": targets [map_key "k"], exists=false
//	               => holds. targets [map_key "k"], want.value => fails.
//
// insert — create WITHOUT overwriting. An existing value is an error, which is
// what distinguishes insert from assign.
//
//	message field  set the field only if it is currently absent; otherwise
//	               error. A field is "already set" if it is set, or if it
//	               belongs to a target `oneof` that already has a member set.
//	list index     insert BEFORE the index, shifting the remainder right.
//	               Use `Selector.append` to add at the end.
//	map key        add the entry only if the key is absent; otherwise error.
//	container      message: set only the fields of `value` that are currently
//	               absent; a field already set (by the rule above) is an error.
//	               list: append every element of `value` (which must be `l`).
//	               map: add every entry of `value` (which must be `map`); a key
//	               already present is an error.
//
// assign — set the target to a literal, creating or overwriting as needed.
//
//	message field  set the field.
//	list index     overwrite the element in place. The index must be in range;
//	               assign never grows a list (use insert with `append`).
//	map key        set the entry, creating it if absent — an empty slot is
//	               what assign is for, not a missing target.
//	container      replace wholesale: clear the container, then apply `value`.
//	               The value's kind must match the container (`m`/`l`/`map`).
//
// move — read the value at `from`, write it to every target, then clear the
// source.
//
//	A target is written with ASSIGN semantics: an occupied target is
//	overwritten. `move` never inserts, except at `Selector.append`.
//	message field  set the field, overwriting if already set.
//	list index     overwrite the element in place; the list does not grow.
//	               With `Selector.append`, append after the last element.
//	map key        set the entry, creating it if absent.
//	container      error. Moving a value onto a container is not defined.
//	The source is resolved, and its value read, BEFORE any target is written,
//	so the result does not depend on target order. The source and every target
//	must have the same kind (see the table on `Value`) AND the same declared
//	type: the same fully-qualified message or enum name for `m` and `e`, the
//	same element kind and type for `l`, and the same key and value types for
//	`map`. There is no conversion and no reinterpretation of an enum number
//	across enum types.
//	Clearing the source uses the `remove` rule for the SOURCE's own container —
//	a message field is cleared, a list element is removed and the list shrinks,
//	a map entry is deleted — and happens once, after every target has been
//	written, against the source position as it was resolved before the entry
//	began.
//	If a target resolves to the source location, the entry is a NO-OP for that
//	target and the source is NOT cleared (RFC 6902 §4.4).
//
// copy — as `move`, but the source is left in place.
//
//	container      error.
//
// nest — apply an inner Delta to the target, which must be a container.
//
//	The inner Delta's `Key`s are interpreted relative to that container:
//	fields for a message, indices for a list, keys for a map. Targeting a
//	scalar is an error.
//	container      apply the inner Delta to the container reached by `path`.
//
// =================================================================
type Entry struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path         *Path                  `protobuf:"bytes,1,opt,name=path"`
	xxx_hidden_Scope        isEntry_Scope          `protobuf_oneof:"scope"`
	xxx_hidden_OnMissing    OnMissing              `protobuf:"varint,4,opt,name=on_missing,json=onMissing,enum=patch.OnMissing"`
	xxx_hidden_OnAbsentPath OnAbsentPath           `protobuf:"varint,5,opt,name=on_absent_path,json=onAbsentPath,enum=patch.OnAbsentPath"`
	xxx_hidden_Kind         isEntry_Kind           `protobuf_oneof:"kind"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_patch_patch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Entry) GetPath() *Path {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return nil
}

func (x *Entry) GetTargets() *Targets {
	if x != nil {
		if x, ok := x.xxx_hidden_Scope.(*entry_Targets); ok {
			return x.Targets
		}
	}
	return nil
}

func (x *Entry) GetContainer() *Container {
	if x != nil {
		if x, ok := x.xxx_hidden_Scope.(*entry_Container); ok {
			return x.Container
		}
	}
	return nil
}

func (x *Entry) GetOnMissing() OnMissing {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_OnMissing
		}
	}
	return OnMissing_ON_MISSING_UNSPECIFIED
}

func (x *Entry) GetOnAbsentPath() OnAbsentPath {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_OnAbsentPath
		}
	}
	return OnAbsentPath_ON_ABSENT_PATH_UNSPECIFIED
}

func (x *Entry) GetRemove() *Remove {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Remove); ok {
			return x.Remove
		}
	}
	return nil
}

func (x *Entry) GetTest() *Test {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Test); ok {
			return x.Test
		}
	}
	return nil
}

func (x *Entry) GetInsert() *Insert {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Insert); ok {
			return x.Insert
		}
	}
	return nil
}

func (x *Entry) GetAssign() *Assign {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *Entry) GetMove() *Move {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *Entry) GetCopy() *Copy {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Copy); ok {
			return x.Copy
		}
	}
	return nil
}

func (x *Entry) GetNest() *Nest {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Nest); ok {
			return x.Nest
		}
	}
	return nil
}

func (x *Entry) SetPath(v *Path) {
	x.xxx_hidden_Path = v
}

func (x *Entry) SetTargets(v *Targets) {
	if v == nil {
		x.xxx_hidden_Scope = nil
		return
	}
	x.xxx_hidden_Scope = &entry_Targets{v}
}

func (x *Entry) SetContainer(v *Container) {
	if v == nil {
		x.xxx_hidden_Scope = nil
		return
	}
	x.xxx_hidden_Scope = &entry_Container{v}
}

func (x *Entry) SetOnMissing(v OnMissing) {
	x.xxx_hidden_OnMissing = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Entry) SetOnAbsentPath(v OnAbsentPath) {
	x.xxx_hidden_OnAbsentPath = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Entry) SetRemove(v *Remove) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Remove{v}
}

func (x *Entry) SetTest(v *Test) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Test{v}
}

func (x *Entry) SetInsert(v *Insert) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Insert{v}
}

func (x *Entry) SetAssign(v *Assign) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Assign{v}
}

func (x *Entry) SetMove(v *Move) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Move{v}
}

func (x *Entry) SetCopy(v *Copy) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Copy{v}
}

func (x *Entry) SetNest(v *Nest) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Nest{v}
}

func (x *Entry) HasPath() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Path != nil
}

func (x *Entry) HasScope() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Scope != nil
}

func (x *Entry) HasTargets() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Scope.(*entry_Targets)
	return ok
}

func (x *Entry) HasContainer() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Scope.(*entry_Container)
	return ok
}

func (x *Entry) HasOnMissing() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Entry) HasOnAbsentPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Entry) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Entry) HasRemove() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Remove)
	return ok
}

func (x *Entry) HasTest() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Test)
	return ok
}

func (x *Entry) HasInsert() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Insert)
	return ok
}

func (x *Entry) HasAssign() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Assign)
	return ok
}

func (x *Entry) HasMove() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Move)
	return ok
}

func (x *Entry) HasCopy() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Copy)
	return ok
}

func (x *Entry) HasNest() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Nest)
	return ok
}

func (x *Entry) ClearPath() {
	x.xxx_hidden_Path = nil
}

func (x *Entry) ClearScope() {
	x.xxx_hidden_Scope = nil
}

func (x *Entry) ClearTargets() {
	if _, ok := x.xxx_hidden_Scope.(*entry_Targets); ok {
		x.xxx_hidden_Scope = nil
	}
}

func (x *Entry) ClearContainer() {
	if _, ok := x.xxx_hidden_Scope.(*entry_Container); ok {
		x.xxx_hidden_Scope = nil
	}
}

func (x *Entry) ClearOnMissing() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_OnMissing = OnMissing_ON_MISSING_UNSPECIFIED
}

func (x *Entry) ClearOnAbsentPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_OnAbsentPath = OnAbsentPath_ON_ABSENT_PATH_UNSPECIFIED
}

func (x *Entry) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Entry) ClearRemove() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Remove); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearTest() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Test); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearInsert() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Insert); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearAssign() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Assign); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearMove() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Move); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearCopy() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Copy); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearNest() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Nest); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Entry_Scope_not_set_case case_Entry_Scope = 0
const Entry_Targets_case case_Entry_Scope = 2
const Entry_Container_case case_Entry_Scope = 3

func (x *Entry) WhichScope() case_Entry_Scope {
	if x == nil {
		return Entry_Scope_not_set_case
	}
	switch x.xxx_hidden_Scope.(type) {
	case *entry_Targets:
		return Entry_Targets_case
	case *entry_Container:
		return Entry_Container_case
	default:
		return Entry_Scope_not_set_case
	}
}

const Entry_Kind_not_set_case case_Entry_Kind = 0
const Entry_Remove_case case_Entry_Kind = 6
const Entry_Test_case case_Entry_Kind = 7
const Entry_Insert_case case_Entry_Kind = 8
const Entry_Assign_case case_Entry_Kind = 9
const Entry_Move_case case_Entry_Kind = 10
const Entry_Copy_case case_Entry_Kind = 11
const Entry_Nest_case case_Entry_Kind = 12

func (x *Entry) WhichKind() case_Entry_Kind {
	if x == nil {
		return Entry_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *entry_Remove:
		return Entry_Remove_case
	case *entry_Test:
		return Entry_Test_case
	case *entry_Insert:
		return Entry_Insert_case
	case *entry_Assign:
		return Entry_Assign_case
	case *entry_Move:
		return Entry_Move_case
	case *entry_Copy:
		return Entry_Copy_case
	case *entry_Nest:
		return Entry_Nest_case
	default:
		return Entry_Kind_not_set_case
	}
}

type Entry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Navigate into a nested container before applying. Empty addresses the
	// container this Delta is applied to. Every container along the way must
	// already exist.
	Path *Path
	// What the operation applies to. Required — an entry with no scope is an
	// error. Root behavior is NOT derived from an empty target list.

	// Fields of oneof xxx_hidden_Scope:
	// The listed locations within the container reached by `path`.
	Targets *Targets
	// The container reached by `path`, as a whole.
	Container *Container
	// -- end of xxx_hidden_Scope
	// How to treat a MISSING target (see `Key`). Defaults to fail.
	//
	// This governs ONLY missing `Selector` targets, and only for kinds other than
	// `test`. It never applies to `Entry.path`, to a `Location`, to unrecognized
	// arms or unknown fields, to kind or declared-type mismatches, to a `Field`
	// whose identifiers disagree, or to a failed `test`.
	OnMissing *OnMissing
	// How to treat a container along `path` that does not exist. Defaults to
	// fail, which is the rule stated on `Path`.
	//
	// This governs ONLY `Entry.path`, and only for kinds other than `test`. It
	// does NOT reach `Location.path`: creating a source container would mean
	// reading from something the entry had just made empty, which is either an
	// error or a no-op whichever way it is defined.
	//
	// It may not be set on a `test`. Creating a container is a mutation, and a
	// `test` MUST NOT mutate — a passing test would otherwise leave the target
	// holding a container the document never asked for.
	OnAbsentPath *OnAbsentPath
	// Exactly one operation. Required.

	// Fields of oneof xxx_hidden_Kind:
	Remove *Remove
	Test   *Test
	Insert *Insert
	Assign *Assign
	Move   *Move
	Copy   *Copy
	Nest   *Nest
	// -- end of xxx_hidden_Kind
}

func (b0 Entry_builder) Build() *Entry {
	m0 := &Entry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	if b.Targets != nil {
		x.xxx_hidden_Scope = &entry_Targets{b.Targets}
	}
	if b.Container != nil {
		x.xxx_hidden_Scope = &entry_Container{b.Container}
	}
	if b.OnMissing != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_OnMissing = *b.OnMissing
	}
	if b.OnAbsentPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_OnAbsentPath = *b.OnAbsentPath
	}
	if b.Remove != nil {
		x.xxx_hidden_Kind = &entry_Remove{b.Remove}
	}
	if b.Test != nil {
		x.xxx_hidden_Kind = &entry_Test{b.Test}
	}
	if b.Insert != nil {
		x.xxx_hidden_Kind = &entry_Insert{b.Insert}
	}
	if b.Assign != nil {
		x.xxx_hidden_Kind = &entry_Assign{b.Assign}
	}
	if b.Move != nil {
		x.xxx_hidden_Kind = &entry_Move{b.Move}
	}
	if b.Copy != nil {
		x.xxx_hidden_Kind = &entry_Copy{b.Copy}
	}
	if b.Nest != nil {
		x.xxx_hidden_Kind = &entry_Nest{b.Nest}
	}
	return m0
}

type case_Entry_Scope protoreflect.FieldNumber

func (x case_Entry_Scope) String() string {
	md := file_patch_patch_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type case_Entry_Kind protoreflect.FieldNumber

func (x case_Entry_Kind) String() string {
	md := file_patch_patch_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isEntry_Scope interface {
	isEntry_Scope()
}

type entry_Targets struct {
	// The listed locations within the container reached by `path`.
	Targets *Targets `protobuf:"bytes,2,opt,name=targets,oneof"`
}

type entry_Container struct {
	// The container reached by `path`, as a whole.
	Container *Container `protobuf:"bytes,3,opt,name=container,oneof"`
}

func (*entry_Targets) isEntry_Scope() {}

func (*entry_Container) isEntry_Scope() {}

type isEntry_Kind interface {
	isEntry_Kind()
}

type entry_Remove struct {
	Remove *Remove `protobuf:"bytes,6,opt,name=remove,oneof"`
}

type entry_Test struct {
	Test *Test `protobuf:"bytes,7,opt,name=test,oneof"`
}

type entry_Insert struct {
	Insert *Insert `protobuf:"bytes,8,opt,name=insert,oneof"`
}

type entry_Assign struct {
	Assign *Assign `protobuf:"bytes,9,opt,name=assign,oneof"`
}

type entry_Move struct {
	Move *Move `protobuf:"bytes,10,opt,name=move,oneof"`
}

type entry_Copy struct {
	Copy *Copy `protobuf:"bytes,11,opt,name=copy,oneof"`
}

type entry_Nest struct {
	Nest *Nest `protobuf:"bytes,12,opt,name=nest,oneof"`
}

func (*entry_Remove) isEntry_Kind() {}

func (*entry_Test) isEntry_Kind() {}

func (*entry_Insert) isEntry_Kind() {}

func (*entry_Assign) isEntry_Kind() {}

func (*entry_Move) isEntry_Kind() {}

func (*entry_Copy) isEntry_Kind() {}

func (*entry_Nest) isEntry_Kind() {}

// Targets lists the locations an operation applies to. `selectors` must not be
// empty; address the container with `Entry.container` instead.
type Targets struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Selectors *[]*Selector           `protobuf:"bytes,1,rep,name=selectors"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Targets) Reset() {
	*x = Targets{}
	mi := &file_patch_patch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Targets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Targets) ProtoMessage() {}

func (x *Targets) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Targets) GetSelectors() []*Selector {
	if x != nil {
		if x.xxx_hidden_Selectors != nil {
			return *x.xxx_hidden_Selectors
		}
	}
	return nil
}

func (x *Targets) SetSelectors(v []*Selector) {
	x.xxx_hidden_Selectors = &v
}

type Targets_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Selectors []*Selector
}

func (b0 Targets_builder) Build() *Targets {
	m0 := &Targets{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Selectors = &b.Selectors
	return m0
}

// Container addresses the container reached by `Entry.path` as a whole. It
// carries no data; it is a message rather than a bool so that it can gain
// options later without changing `Entry.scope`.
type Container struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_patch_patch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Container_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Container_builder) Build() *Container {
	m0 := &Container{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Remove struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Remove) Reset() {
	*x = Remove{}
	mi := &file_patch_patch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remove) ProtoMessage() {}

func (x *Remove) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Remove_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Remove_builder) Build() *Remove {
	m0 := &Remove{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Test struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Want isTest_Want            `protobuf_oneof:"want"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Test) Reset() {
	*x = Test{}
	mi := &file_patch_patch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Test) GetValue() *Value {
	if x != nil {
		if x, ok := x.xxx_hidden_Want.(*test_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *Test) GetExists() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_Want.(*test_Exists); ok {
			return x.Exists
		}
	}
	return false
}

func (x *Test) SetValue(v *Value) {
	if v == nil {
		x.xxx_hidden_Want = nil
		return
	}
	x.xxx_hidden_Want = &test_Value{v}
}

func (x *Test) SetExists(v bool) {
	x.xxx_hidden_Want = &test_Exists{v}
}

func (x *Test) HasWant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Want != nil
}

func (x *Test) HasValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Want.(*test_Value)
	return ok
}

func (x *Test) HasExists() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Want.(*test_Exists)
	return ok
}

func (x *Test) ClearWant() {
	x.xxx_hidden_Want = nil
}

func (x *Test) ClearValue() {
	if _, ok := x.xxx_hidden_Want.(*test_Value); ok {
		x.xxx_hidden_Want = nil
	}
}

func (x *Test) ClearExists() {
	if _, ok := x.xxx_hidden_Want.(*test_Exists); ok {
		x.xxx_hidden_Want = nil
	}
}

const Test_Want_not_set_case case_Test_Want = 0
const Test_Value_case case_Test_Want = 1
const Test_Exists_case case_Test_Want = 2

func (x *Test) WhichWant() case_Test_Want {
	if x == nil {
		return Test_Want_not_set_case
	}
	switch x.xxx_hidden_Want.(type) {
	case *test_Value:
		return Test_Value_case
	case *test_Exists:
		return Test_Exists_case
	default:
		return Test_Want_not_set_case
	}
}

type Test_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. An unset `want` is an error, never a passing assertion.

	// Fields of oneof xxx_hidden_Want:
	// The target exists and equals this value.
	Value *Value
	// true: the target is present. false: the target is absent.
	Exists *bool
	// -- end of xxx_hidden_Want
}

func (b0 Test_builder) Build() *Test {
	m0 := &Test{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Value != nil {
		x.xxx_hidden_Want = &test_Value{b.Value}
	}
	if b.Exists != nil {
		x.xxx_hidden_Want = &test_Exists{*b.Exists}
	}
	return m0
}

type case_Test_Want protoreflect.FieldNumber

func (x case_Test_Want) String() string {
	md := file_patch_patch_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isTest_Want interface {
	isTest_Want()
}

type test_Value struct {
	// The target exists and equals this value.
	Value *Value `protobuf:"bytes,1,opt,name=value,oneof"`
}

type test_Exists struct {
	// true: the target is present. false: the target is absent.
	Exists bool `protobuf:"varint,2,opt,name=exists,oneof"`
}

func (*test_Value) isTest_Want() {}

func (*test_Exists) isTest_Want() {}

type Insert struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value *Value                 `protobuf:"bytes,1,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Insert) Reset() {
	*x = Insert{}
	mi := &file_patch_patch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Insert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insert) ProtoMessage() {}

func (x *Insert) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Insert) GetValue() *Value {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *Insert) SetValue(v *Value) {
	x.xxx_hidden_Value = v
}

func (x *Insert) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *Insert) ClearValue() {
	x.xxx_hidden_Value = nil
}

type Insert_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required.
	Value *Value
}

func (b0 Insert_builder) Build() *Insert {
	m0 := &Insert{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

type Assign struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value *Value                 `protobuf:"bytes,1,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Assign) Reset() {
	*x = Assign{}
	mi := &file_patch_patch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assign) ProtoMessage() {}

func (x *Assign) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Assign) GetValue() *Value {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *Assign) SetValue(v *Value) {
	x.xxx_hidden_Value = v
}

func (x *Assign) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *Assign) ClearValue() {
	x.xxx_hidden_Value = nil
}

type Assign_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required.
	Value *Value
}

func (b0 Assign_builder) Build() *Assign {
	m0 := &Assign{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

type Move struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_From *Location              `protobuf:"bytes,1,opt,name=from"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_patch_patch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Move) GetFrom() *Location {
	if x != nil {
		return x.xxx_hidden_From
	}
	return nil
}

func (x *Move) SetFrom(v *Location) {
	x.xxx_hidden_From = v
}

func (x *Move) HasFrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_From != nil
}

func (x *Move) ClearFrom() {
	x.xxx_hidden_From = nil
}

type Move_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required.
	From *Location
}

func (b0 Move_builder) Build() *Move {
	m0 := &Move{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_From = b.From
	return m0
}

type Copy struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_From *Location              `protobuf:"bytes,1,opt,name=from"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Copy) Reset() {
	*x = Copy{}
	mi := &file_patch_patch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Copy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Copy) ProtoMessage() {}

func (x *Copy) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Copy) GetFrom() *Location {
	if x != nil {
		return x.xxx_hidden_From
	}
	return nil
}

func (x *Copy) SetFrom(v *Location) {
	x.xxx_hidden_From = v
}

func (x *Copy) HasFrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_From != nil
}

func (x *Copy) ClearFrom() {
	x.xxx_hidden_From = nil
}

type Copy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required.
	From *Location
}

func (b0 Copy_builder) Build() *Copy {
	m0 := &Copy{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_From = b.From
	return m0
}

type Nest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Delta *Delta                 `protobuf:"bytes,1,opt,name=delta"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Nest) Reset() {
	*x = Nest{}
	mi := &file_patch_patch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nest) ProtoMessage() {}

func (x *Nest) ProtoReflect() protoreflect.Message {
	mi := &file_patch_patch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Nest) GetDelta() *Delta {
	if x != nil {
		return x.xxx_hidden_Delta
	}
	return nil
}

func (x *Nest) SetDelta(v *Delta) {
	x.xxx_hidden_Delta = v
}

func (x *Nest) HasDelta() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Delta != nil
}

func (x *Nest) ClearDelta() {
	x.xxx_hidden_Delta = nil
}

type Nest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required; must be non-empty.
	Delta *Delta
}

func (b0 Nest_builder) Build() *Nest {
	m0 := &Nest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Delta = b.Delta
	return m0
}

var File_patch_patch_proto protoreflect.FileDescriptor

const file_patch_patch_proto_rawDesc = "" +
	"\n" +
	"\x11patch/patch.proto\x12\x05patch\x1a\x10patch/path.proto\x1a\x11patch/value.proto\"~\n" +
	"\x05Patch\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12.\n" +
	"\x13min_reader_revision\x18\x02 \x01(\rR\x11minReaderRevision\x12\"\n" +
	"\x05delta\x18\x03 \x01(\v2\f.patch.DeltaR\x05delta\"/\n" +
	"\x05Delta\x12&\n" +
	"\aentries\x18\x01 \x03(\v2\f.patch.EntryR\aentries\"\x90\x04\n" +
	"\x05Entry\x12\x1f\n" +
	"\x04path\x18\x01 \x01(\v2\v.patch.PathR\x04path\x12*\n" +
	"\atargets\x18\x02 \x01(\v2\x0e.patch.TargetsH\x00R\atargets\x120\n" +
	"\tcontainer\x18\x03 \x01(\v2\x10.patch.ContainerH\x00R\tcontainer\x12/\n" +
	"\n" +
	"on_missing\x18\x04 \x01(\x0e2\x10.patch.OnMissingR\tonMissing\x129\n" +
	"\x0eon_absent_path\x18\x05 \x01(\x0e2\x13.patch.OnAbsentPathR\fonAbsentPath\x12'\n" +
	"\x06remove\x18\x06 \x01(\v2\r.patch.RemoveH\x01R\x06remove\x12!\n" +
	"\x04test\x18\a \x01(\v2\v.patch.TestH\x01R\x04test\x12'\n" +
	"\x06insert\x18\b \x01(\v2\r.patch.InsertH\x01R\x06insert\x12'\n" +
	"\x06assign\x18\t \x01(\v2\r.patch.AssignH\x01R\x06assign\x12!\n" +
	"\x04move\x18\n" +
	" \x01(\v2\v.patch.MoveH\x01R\x04move\x12!\n" +
	"\x04copy\x18\v \x01(\v2\v.patch.CopyH\x01R\x04copy\x12!\n" +
	"\x04nest\x18\f \x01(\v2\v.patch.NestH\x01R\x04nestB\a\n" +
	"\x05scopeB\x06\n" +
	"\x04kindJ\x04\b\r\x10\x10\"8\n" +
	"\aTargets\x12-\n" +
	"\tselectors\x18\x01 \x03(\v2\x0f.patch.SelectorR\tselectors\"\v\n" +
	"\tContainer\"\b\n" +
	"\x06Remove\"T\n" +
	"\x04Test\x12$\n" +
	"\x05value\x18\x01 \x01(\v2\f.patch.ValueH\x00R\x05value\x12\x18\n" +
	"\x06exists\x18\x02 \x01(\bH\x00R\x06existsB\x06\n" +
	"\x04wantJ\x04\b\x03\x10\x10\",\n" +
	"\x06Insert\x12\"\n" +
	"\x05value\x18\x01 \x01(\v2\f.patch.ValueR\x05value\",\n" +
	"\x06Assign\x12\"\n" +
	"\x05value\x18\x01 \x01(\v2\f.patch.ValueR\x05value\"+\n" +
	"\x04Move\x12#\n" +
	"\x04from\x18\x01 \x01(\v2\x0f.patch.LocationR\x04from\"+\n" +
	"\x04Copy\x12#\n" +
	"\x04from\x18\x01 \x01(\v2\x0f.patch.LocationR\x04from\"*\n" +
	"\x04Nest\x12\"\n" +
	"\x05delta\x18\x01 \x01(\v2\f.patch.DeltaR\x05delta*I\n" +
	"\fOnAbsentPath\x12\x1e\n" +
	"\x1aON_ABSENT_PATH_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ON_ABSENT_PATH_CREATE\x10\x01*<\n" +
	"\tOnMissing\x12\x1a\n" +
	"\x16ON_MISSING_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fON_MISSING_SKIP\x10\x01B3Z*github.com/lesomnus/protobuf-patch/patchpb\x92\x03\x04\b\x01\x10\x01b\beditionsp\xe8\a"

var file_patch_patch_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_patch_patch_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_patch_patch_proto_goTypes = []any{
	(OnAbsentPath)(0), // 0: patch.OnAbsentPath
	(OnMissing)(0),    // 1: patch.OnMissing
	(*Patch)(nil),     // 2: patch.Patch
	(*Delta)(nil),     // 3: patch.Delta
	(*Entry)(nil),     // 4: patch.Entry
	(*Targets)(nil),   // 5: patch.Targets
	(*Container)(nil), // 6: patch.Container
	(*Remove)(nil),    // 7: patch.Remove
	(*Test)(nil),      // 8: patch.Test
	(*Insert)(nil),    // 9: patch.Insert
	(*Assign)(nil),    // 10: patch.Assign
	(*Move)(nil),      // 11: patch.Move
	(*Copy)(nil),      // 12: patch.Copy
	(*Nest)(nil),      // 13: patch.Nest
	(*Path)(nil),      // 14: patch.Path
	(*Selector)(nil),  // 15: patch.Selector
	(*Value)(nil),     // 16: patch.Value
	(*Location)(nil),  // 17: patch.Location
}
var file_patch_patch_proto_depIdxs = []int32{
	3,  // 0: patch.Patch.delta:type_name -> patch.Delta
	4,  // 1: patch.Delta.entries:type_name -> patch.Entry
	14, // 2: patch.Entry.path:type_name -> patch.Path
	5,  // 3: patch.Entry.targets:type_name -> patch.Targets
	6,  // 4: patch.Entry.container:type_name -> patch.Container
	1,  // 5: patch.Entry.on_missing:type_name -> patch.OnMissing
	0,  // 6: patch.Entry.on_absent_path:type_name -> patch.OnAbsentPath
	7,  // 7: patch.Entry.remove:type_name -> patch.Remove
	8,  // 8: patch.Entry.test:type_name -> patch.Test
	9,  // 9: patch.Entry.insert:type_name -> patch.Insert
	10, // 10: patch.Entry.assign:type_name -> patch.Assign
	11, // 11: patch.Entry.move:type_name -> patch.Move
	12, // 12: patch.Entry.copy:type_name -> patch.Copy
	13, // 13: patch.Entry.nest:type_name -> patch.Nest
	15, // 14: patch.Targets.selectors:type_name -> patch.Selector
	16, // 15: patch.Test.value:type_name -> patch.Value
	16, // 16: patch.Insert.value:type_name -> patch.Value
	16, // 17: patch.Assign.value:type_name -> patch.Value
	17, // 18: patch.Move.from:type_name -> patch.Location
	17, // 19: patch.Copy.from:type_name -> patch.Location
	3,  // 20: patch.Nest.delta:type_name -> patch.Delta
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_patch_patch_proto_init() }
func file_patch_patch_proto_init() {
	if File_patch_patch_proto != nil {
		return
	}
	file_patch_path_proto_init()
	file_patch_value_proto_init()
	file_patch_patch_proto_msgTypes[2].OneofWrappers = []any{
		(*entry_Targets)(nil),
		(*entry_Container)(nil),
		(*entry_Remove)(nil),
		(*entry_Test)(nil),
		(*entry_Insert)(nil),
		(*entry_Assign)(nil),
		(*entry_Move)(nil),
		(*entry_Copy)(nil),
		(*entry_Nest)(nil),
	}
	file_patch_patch_proto_msgTypes[6].OneofWrappers = []any{
		(*test_Value)(nil),
		(*test_Exists)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patch_patch_proto_rawDesc), len(file_patch_patch_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patch_patch_proto_goTypes,
		DependencyIndexes: file_patch_patch_proto_depIdxs,
		EnumInfos:         file_patch_patch_proto_enumTypes,
		MessageInfos:      file_patch_patch_proto_msgTypes,
	}.Build()
	File_patch_patch_proto = out.File
	file_patch_patch_proto_goTypes = nil
	file_patch_patch_proto_depIdxs = nil
}
