// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: patch/path.proto

package patchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Key names EXACTLY ONE location inside a container.
//
// The `kind` arm must match the container it is resolved against:
//
//	container   | legal arm
//	------------+-----------------------------------------------
//	message     | field
//	list        | index
//	map         | map_key (matching the map's declared key type)
//
// Using an arm that does not match the container is an unconditional error.
//
// VACANCY. A Key can fail to reach existing content in two different ways, and
// the difference decides what an operation may do about it.
//
//   - NO SLOT — the address names no position at all: a field the message does
//     not declare, or an index outside [0, len). Nothing can ever be written
//     there, so every operation treats it as a MISSING TARGET.
//   - EMPTY SLOT — the address names a position that exists but holds nothing:
//     a map key with no entry under it. Every key of the map's declared type
//     is a valid address, so `assign` fills one (this is how a map entry comes
//     into existence at all) and `insert` requires it to be empty. Only
//     `remove` and `nest`, which need something already there, treat it as a
//     missing target.
//
// A declared message field is neither. It always exists as a position; whether
// it currently holds a value is PRESENCE, which is what `Test.want.exists`
// reports and which no operation treats as a missing target.
//
// A missing target is not itself a failure. What happens to one depends on
// where the Key appears:
//
//   - In `Selector.key` under `test`: it is READ. This is exactly what
//     `Test.want.exists` reports, and `Entry.on_missing` never applies.
//   - In `Selector.key` under any other kind: `Entry.on_missing` decides
//     (default: fail).
//   - In `Path.segments` or in `Location`: an unconditional error.
//     `Entry.on_missing` reaches only `Selector` targets.
//
// Key is deliberately single-valued: it is the only segment type permitted in
// `Path`, because a path must reach exactly one container. Multi-valued
// segments live in `Selector`, which is permitted only in `Entry.targets`.
type Key struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind isKey_Kind             `protobuf_oneof:"kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_patch_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_patch_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Key) GetField() *Field {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*key_Field); ok {
			return x.Field
		}
	}
	return nil
}

func (x *Key) GetIndex() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*key_Index); ok {
			return x.Index
		}
	}
	return 0
}

func (x *Key) GetMapKey() *MapKey {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*key_MapKey); ok {
			return x.MapKey
		}
	}
	return nil
}

func (x *Key) SetField(v *Field) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &key_Field{v}
}

func (x *Key) SetIndex(v int64) {
	x.xxx_hidden_Kind = &key_Index{v}
}

func (x *Key) SetMapKey(v *MapKey) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &key_MapKey{v}
}

func (x *Key) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Key) HasField() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*key_Field)
	return ok
}

func (x *Key) HasIndex() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*key_Index)
	return ok
}

func (x *Key) HasMapKey() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*key_MapKey)
	return ok
}

func (x *Key) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Key) ClearField() {
	if _, ok := x.xxx_hidden_Kind.(*key_Field); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Key) ClearIndex() {
	if _, ok := x.xxx_hidden_Kind.(*key_Index); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Key) ClearMapKey() {
	if _, ok := x.xxx_hidden_Kind.(*key_MapKey); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Key_Kind_not_set_case case_Key_Kind = 0
const Key_Field_case case_Key_Kind = 1
const Key_Index_case case_Key_Kind = 2
const Key_MapKey_case case_Key_Kind = 3

func (x *Key) WhichKind() case_Key_Kind {
	if x == nil {
		return Key_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *key_Field:
		return Key_Field_case
	case *key_Index:
		return Key_Index_case
	case *key_MapKey:
		return Key_MapKey_case
	default:
		return Key_Kind_not_set_case
	}
}

type Key_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Kind:
	// A field of a message.
	Field *Field
	// An element of a list.
	//
	// Negative values count from the end: the effective index is `len + index`.
	// This holds for EVERY operation — there is no per-operation off-by-one.
	// "One past the end" is not expressible here; use `Selector.append`.
	//
	// An index outside `[0, len)` after normalization names NO SLOT (above).
	Index *int64
	// An entry of a map.
	MapKey *MapKey
	// -- end of xxx_hidden_Kind
}

func (b0 Key_builder) Build() *Key {
	m0 := &Key{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Field != nil {
		x.xxx_hidden_Kind = &key_Field{b.Field}
	}
	if b.Index != nil {
		x.xxx_hidden_Kind = &key_Index{*b.Index}
	}
	if b.MapKey != nil {
		x.xxx_hidden_Kind = &key_MapKey{b.MapKey}
	}
	return m0
}

type case_Key_Kind protoreflect.FieldNumber

func (x case_Key_Kind) String() string {
	md := file_patch_path_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isKey_Kind interface {
	isKey_Kind()
}

type key_Field struct {
	// A field of a message.
	Field *Field `protobuf:"bytes,1,opt,name=field,oneof"`
}

type key_Index struct {
	// An element of a list.
	//
	// Negative values count from the end: the effective index is `len + index`.
	// This holds for EVERY operation — there is no per-operation off-by-one.
	// "One past the end" is not expressible here; use `Selector.append`.
	//
	// An index outside `[0, len)` after normalization names NO SLOT (above).
	Index int64 `protobuf:"zigzag64,2,opt,name=index,oneof"`
}

type key_MapKey struct {
	// An entry of a map.
	MapKey *MapKey `protobuf:"bytes,3,opt,name=map_key,json=mapKey,oneof"`
}

func (*key_Field) isKey_Kind() {}

func (*key_Index) isKey_Kind() {}

func (*key_MapKey) isKey_Kind() {}

// Field identifies a message field. It is a CONSTRAINT, not a mere selector:
// every identifier that is set must agree, and disagreement is an error rather
// than a fallback. This is what lets a stored Patch refuse to apply to a
// message whose fields were renamed or renumbered underneath it.
//
// Resolution, in order:
//  1. If `number` is set, resolve by number. Otherwise if `name` is set,
//     resolve by name. Otherwise resolve by `json_name`.
//     (`number` goes first because the field number is protobuf's stable
//     identity; names may be edited without a wire break.)
//  2. Every OTHER identifier that is set must equal the corresponding property
//     of the resolved field. Any disagreement is an error — NOT a vacancy, and
//     never subject to `Entry.on_missing`. Disagreement means the Patch was
//     authored against a different schema; that must never be skipped.
//
// If no identifier resolves to a declared field, the Key names NO SLOT (see
// `Key`), which every operation treats as a missing target.
//
// EXTENSIONS ARE NOT ADDRESSABLE, and are not vacancy either. A `number` that
// falls in one of the target message's extension ranges is an ERROR, never
// subject to `Entry.on_missing`. An extension is data the message really
// holds: calling it a missing target would let `test.exists = false` succeed
// about a value that is present, and would let `on_missing` silently skip an
// operation that was meant to change it. Both are exactly the outcomes this
// format exists to prevent, so it refuses rather than answers wrongly. An
// extension the reader has no descriptor for arrives as an unknown field on
// the target instead, and the preservation rule in `patch.Patch` already
// covers it. Should a revision make extensions addressable, it will do so with
// its own arm rather than by reinterpreting `number`.
//
// A Field with no identifier set is an error. A set-but-empty `name` or
// `json_name` is an error, since neither is a legal protobuf field name.
type Field struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_JsonName    *string                `protobuf:"bytes,2,opt,name=json_name,json=jsonName"`
	xxx_hidden_Number      uint32                 `protobuf:"varint,3,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_patch_path_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_patch_path_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Field) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Field) GetJsonName() string {
	if x != nil {
		if x.xxx_hidden_JsonName != nil {
			return *x.xxx_hidden_JsonName
		}
		return ""
	}
	return ""
}

func (x *Field) GetNumber() uint32 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *Field) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Field) SetJsonName(v string) {
	x.xxx_hidden_JsonName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Field) SetNumber(v uint32) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Field) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Field) HasJsonName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Field) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Field) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Field) ClearJsonName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_JsonName = nil
}

func (x *Field) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Number = 0
}

type Field_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The field's declared name, e.g. "user_id".
	Name *string
	// The field's ProtoJSON name, e.g. "userId" — the value of the field's
	// `json_name` if set, otherwise the lowerCamelCase derivation of `name`.
	// Set this when the patch is authored against a JSON view of the message.
	// It may be set alone, or together with `name`/`number` as a constraint.
	JsonName *string
	// The field number. Must be >= 1; 0 is not a legal field number.
	Number *uint32
}

func (b0 Field_builder) Build() *Field {
	m0 := &Field{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Name = b.Name
	}
	if b.JsonName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_JsonName = b.JsonName
	}
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

// MapKey identifies a map entry. The arm MUST match the map's declared key
// type; a mismatch is an error and is never coerced. In particular a numeric
// arm is NOT stringified onto a string-keyed map.
//
//	declared key type              | arm
//	-------------------------------+-----
//	string                         | s
//	int32, sint32, sfixed32        | i
//	int64, sint64, sfixed64        | i
//	uint32, fixed32                | u
//	uint64, fixed64                | u
//	bool                           | b
//
// (These are exactly protobuf's legal map key types; float, double, bytes,
// enum, and message keys do not exist.)
//
// The carried value MUST also lie within the declared key type's range: `i`
// against a `map<int32, V>` must lie in [-2^31, 2^31), `u` against a
// `map<uint32, V>` in [0, 2^32). A value outside that range is an ERROR — it
// is never truncated, and it is never a merely missing key that
// `Entry.on_missing` can skip.
//
// The empty string is a legal `s` key and is unambiguous here, because the
// oneof carries its own presence.
type MapKey struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind isMapKey_Kind          `protobuf_oneof:"kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MapKey) Reset() {
	*x = MapKey{}
	mi := &file_patch_path_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapKey) ProtoMessage() {}

func (x *MapKey) ProtoReflect() protoreflect.Message {
	mi := &file_patch_path_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MapKey) GetS() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*mapKey_S); ok {
			return x.S
		}
	}
	return ""
}

func (x *MapKey) GetI() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*mapKey_I); ok {
			return x.I
		}
	}
	return 0
}

func (x *MapKey) GetU() uint64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*mapKey_U); ok {
			return x.U
		}
	}
	return 0
}

func (x *MapKey) GetB() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*mapKey_B); ok {
			return x.B
		}
	}
	return false
}

func (x *MapKey) SetS(v string) {
	x.xxx_hidden_Kind = &mapKey_S{v}
}

func (x *MapKey) SetI(v int64) {
	x.xxx_hidden_Kind = &mapKey_I{v}
}

func (x *MapKey) SetU(v uint64) {
	x.xxx_hidden_Kind = &mapKey_U{v}
}

func (x *MapKey) SetB(v bool) {
	x.xxx_hidden_Kind = &mapKey_B{v}
}

func (x *MapKey) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *MapKey) HasS() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*mapKey_S)
	return ok
}

func (x *MapKey) HasI() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*mapKey_I)
	return ok
}

func (x *MapKey) HasU() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*mapKey_U)
	return ok
}

func (x *MapKey) HasB() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*mapKey_B)
	return ok
}

func (x *MapKey) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *MapKey) ClearS() {
	if _, ok := x.xxx_hidden_Kind.(*mapKey_S); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *MapKey) ClearI() {
	if _, ok := x.xxx_hidden_Kind.(*mapKey_I); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *MapKey) ClearU() {
	if _, ok := x.xxx_hidden_Kind.(*mapKey_U); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *MapKey) ClearB() {
	if _, ok := x.xxx_hidden_Kind.(*mapKey_B); ok {
		x.xxx_hidden_Kind = nil
	}
}

const MapKey_Kind_not_set_case case_MapKey_Kind = 0
const MapKey_S_case case_MapKey_Kind = 1
const MapKey_I_case case_MapKey_Kind = 2
const MapKey_U_case case_MapKey_Kind = 3
const MapKey_B_case case_MapKey_Kind = 4

func (x *MapKey) WhichKind() case_MapKey_Kind {
	if x == nil {
		return MapKey_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *mapKey_S:
		return MapKey_S_case
	case *mapKey_I:
		return MapKey_I_case
	case *mapKey_U:
		return MapKey_U_case
	case *mapKey_B:
		return MapKey_B_case
	default:
		return MapKey_Kind_not_set_case
	}
}

type MapKey_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Kind:
	S *string
	I *int64
	U *uint64
	B *bool
	// -- end of xxx_hidden_Kind
}

func (b0 MapKey_builder) Build() *MapKey {
	m0 := &MapKey{}
	b, x := &b0, m0
	_, _ = b, x
	if b.S != nil {
		x.xxx_hidden_Kind = &mapKey_S{*b.S}
	}
	if b.I != nil {
		x.xxx_hidden_Kind = &mapKey_I{*b.I}
	}
	if b.U != nil {
		x.xxx_hidden_Kind = &mapKey_U{*b.U}
	}
	if b.B != nil {
		x.xxx_hidden_Kind = &mapKey_B{*b.B}
	}
	return m0
}

type case_MapKey_Kind protoreflect.FieldNumber

func (x case_MapKey_Kind) String() string {
	md := file_patch_path_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isMapKey_Kind interface {
	isMapKey_Kind()
}

type mapKey_S struct {
	S string `protobuf:"bytes,1,opt,name=s,oneof"`
}

type mapKey_I struct {
	I int64 `protobuf:"zigzag64,2,opt,name=i,oneof"`
}

type mapKey_U struct {
	U uint64 `protobuf:"varint,3,opt,name=u,oneof"`
}

type mapKey_B struct {
	B bool `protobuf:"varint,4,opt,name=b,oneof"`
}

func (*mapKey_S) isMapKey_Kind() {}

func (*mapKey_I) isMapKey_Kind() {}

func (*mapKey_U) isMapKey_Kind() {}

func (*mapKey_B) isMapKey_Kind() {}

// Path navigates INTO a nested container before an operation is applied.
//
// A Path is ALWAYS relative to the container that the enclosing `Delta` is
// applied to; for the outermost Delta that is the root message. Empty
// `segments` addresses that container itself. A Path only descends: it can
// never reach a sibling or an ancestor, so a nested Delta cannot escape the
// container that `nest` handed it.
//
// Every container along the path must already exist, and a path that descends
// through a `Key` that reaches nothing is an error. A Patch never auto-creates intermediate
// containers, and `Entry.on_missing` never applies to a Path. (Create a
// container with an explicit `assign` in an earlier entry.)
//
// "Exist" is presence, not contents. A singular message field must be SET; an
// unset one is an error, because descending into it would have to create it.
// A repeated or map field has no presence in protobuf and therefore always
// exists as a container: an empty list or map may be descended into, and the
// operation simply finds nothing there. This is what lets a whole empty list
// be filled by addressing it with `container` scope.
type Path struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Segments *[]*Key                `protobuf:"bytes,1,rep,name=segments"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_patch_path_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_patch_path_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Path) GetSegments() []*Key {
	if x != nil {
		if x.xxx_hidden_Segments != nil {
			return *x.xxx_hidden_Segments
		}
	}
	return nil
}

func (x *Path) SetSegments(v []*Key) {
	x.xxx_hidden_Segments = &v
}

type Path_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Segments []*Key
}

func (b0 Path_builder) Build() *Path {
	m0 := &Path{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Segments = &b.Segments
	return m0
}

// Selector names ZERO OR MORE locations inside a container. It is the segment
// type used by `Entry.targets`.
type Selector struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind isSelector_Kind        `protobuf_oneof:"kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Selector) Reset() {
	*x = Selector{}
	mi := &file_patch_path_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_patch_path_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Selector) GetKey() *Key {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*selector_Key); ok {
			return x.Key
		}
	}
	return nil
}

func (x *Selector) GetRange() *Range {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*selector_Range); ok {
			return x.Range
		}
	}
	return nil
}

func (x *Selector) GetAppend() *Append {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*selector_Append); ok {
			return x.Append
		}
	}
	return nil
}

func (x *Selector) SetKey(v *Key) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &selector_Key{v}
}

func (x *Selector) SetRange(v *Range) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &selector_Range{v}
}

func (x *Selector) SetAppend(v *Append) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &selector_Append{v}
}

func (x *Selector) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Selector) HasKey() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*selector_Key)
	return ok
}

func (x *Selector) HasRange() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*selector_Range)
	return ok
}

func (x *Selector) HasAppend() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*selector_Append)
	return ok
}

func (x *Selector) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Selector) ClearKey() {
	if _, ok := x.xxx_hidden_Kind.(*selector_Key); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Selector) ClearRange() {
	if _, ok := x.xxx_hidden_Kind.(*selector_Range); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Selector) ClearAppend() {
	if _, ok := x.xxx_hidden_Kind.(*selector_Append); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Selector_Kind_not_set_case case_Selector_Kind = 0
const Selector_Key_case case_Selector_Kind = 1
const Selector_Range_case case_Selector_Kind = 2
const Selector_Append_case case_Selector_Kind = 3

func (x *Selector) WhichKind() case_Selector_Kind {
	if x == nil {
		return Selector_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *selector_Key:
		return Selector_Key_case
	case *selector_Range:
		return Selector_Range_case
	case *selector_Append:
		return Selector_Append_case
	default:
		return Selector_Kind_not_set_case
	}
}

type Selector_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Kind:
	// Exactly one location. Legal in every container.
	Key *Key
	// A contiguous span of list elements. Legal ONLY against a list.
	Range *Range
	// The position one past the last list element — the RFC 6901 "-" token.
	// Legal ONLY against a list, and only with `insert`, `move`, and `copy`,
	// each of which can grow a list. It is an error with `remove`, `assign`,
	// `test`, and `nest`, none of which can.
	//
	// This exists so that "append" has its own encoding instead of being
	// smuggled into `Key.index` as a magic value, which is what forces
	// negative indices to mean different things in different operations.
	Append *Append
	// -- end of xxx_hidden_Kind
}

func (b0 Selector_builder) Build() *Selector {
	m0 := &Selector{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		x.xxx_hidden_Kind = &selector_Key{b.Key}
	}
	if b.Range != nil {
		x.xxx_hidden_Kind = &selector_Range{b.Range}
	}
	if b.Append != nil {
		x.xxx_hidden_Kind = &selector_Append{b.Append}
	}
	return m0
}

type case_Selector_Kind protoreflect.FieldNumber

func (x case_Selector_Kind) String() string {
	md := file_patch_path_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSelector_Kind interface {
	isSelector_Kind()
}

type selector_Key struct {
	// Exactly one location. Legal in every container.
	Key *Key `protobuf:"bytes,1,opt,name=key,oneof"`
}

type selector_Range struct {
	// A contiguous span of list elements. Legal ONLY against a list.
	Range *Range `protobuf:"bytes,2,opt,name=range,oneof"`
}

type selector_Append struct {
	// The position one past the last list element — the RFC 6901 "-" token.
	// Legal ONLY against a list, and only with `insert`, `move`, and `copy`,
	// each of which can grow a list. It is an error with `remove`, `assign`,
	// `test`, and `nest`, none of which can.
	//
	// This exists so that "append" has its own encoding instead of being
	// smuggled into `Key.index` as a magic value, which is what forces
	// negative indices to mean different things in different operations.
	Append *Append `protobuf:"bytes,3,opt,name=append,oneof"`
}

func (*selector_Key) isSelector_Kind() {}

func (*selector_Range) isSelector_Kind() {}

func (*selector_Append) isSelector_Kind() {}

// Range selects the list elements in the half-open interval [begin, end).
//
// Normalization, in order:
//  1. `begin` unset => 0.        `end` unset => len.
//  2. A negative bound v => len + v.
//  3. Both bounds are clamped to [0, len].
//
// After normalization, `begin >= end` selects NOTHING. That is a defined
// result, not a failure: the range is well-formed and its answer is empty.
// A Range never wraps around, and never selects a union of two spans — express
// that as two entries in `targets`.
//
// Examples for a list of length 5 (x = selected):
//
//	xxxxx  [_, _)   => [0, 5)   all elements
//	---xx  [-2, _)  => [3, 5)   last two
//	xxx--  [_, -2)  => [0, 3)   all but the last two
//	-xxx-  [1, 4)   => [1, 4)   the middle three
//	-----  [3, 2)   => empty    begin >= end
//	-----  [9, _)   => empty    clamped to [5, 5)
//
// `begin` and `end` share one normalization rule; unset and 0 are distinct.
//
// A Range never produces a missing target: it selects only indices that exist,
// so `Entry.on_missing` has no effect on one.
type Range struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Begin       int64                  `protobuf:"zigzag64,1,opt,name=begin"`
	xxx_hidden_End         int64                  `protobuf:"zigzag64,2,opt,name=end"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_patch_path_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_patch_path_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Range) GetBegin() int64 {
	if x != nil {
		return x.xxx_hidden_Begin
	}
	return 0
}

func (x *Range) GetEnd() int64 {
	if x != nil {
		return x.xxx_hidden_End
	}
	return 0
}

func (x *Range) SetBegin(v int64) {
	x.xxx_hidden_Begin = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Range) SetEnd(v int64) {
	x.xxx_hidden_End = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Range) HasBegin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Range) HasEnd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Range) ClearBegin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Begin = 0
}

func (x *Range) ClearEnd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_End = 0
}

type Range_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Inclusive lower bound. Unset means 0.
	Begin *int64
	// Exclusive upper bound. Unset means the collection length.
	End *int64
}

func (b0 Range_builder) Build() *Range {
	m0 := &Range{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Begin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Begin = *b.Begin
	}
	if b.End != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_End = *b.End
	}
	return m0
}

// Append is the position one past the last element of a list. It carries no
// data; it is a message rather than a bool so that it can gain options later
// without burning a `Selector` arm.
type Append struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Append) Reset() {
	*x = Append{}
	mi := &file_patch_path_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Append) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Append) ProtoMessage() {}

func (x *Append) ProtoReflect() protoreflect.Message {
	mi := &file_patch_path_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Append_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Append_builder) Build() *Append {
	m0 := &Append{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Location names a source position for `move` and `copy`.
//
// It may name a container other than the one holding the targets — this is
// what makes cross-container move/copy expressible — but never one outside the
// enclosing `Delta`'s container.
type Location struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Origin isLocation_Origin      `protobuf_oneof:"origin"`
	xxx_hidden_Key    *Key                   `protobuf:"bytes,2,opt,name=key"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_patch_path_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_patch_path_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Location) GetPath() *Path {
	if x != nil {
		if x, ok := x.xxx_hidden_Origin.(*location_Path); ok {
			return x.Path
		}
	}
	return nil
}

func (x *Location) GetSameContainer() *SameContainer {
	if x != nil {
		if x, ok := x.xxx_hidden_Origin.(*location_SameContainer); ok {
			return x.SameContainer
		}
	}
	return nil
}

func (x *Location) GetKey() *Key {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *Location) SetPath(v *Path) {
	if v == nil {
		x.xxx_hidden_Origin = nil
		return
	}
	x.xxx_hidden_Origin = &location_Path{v}
}

func (x *Location) SetSameContainer(v *SameContainer) {
	if v == nil {
		x.xxx_hidden_Origin = nil
		return
	}
	x.xxx_hidden_Origin = &location_SameContainer{v}
}

func (x *Location) SetKey(v *Key) {
	x.xxx_hidden_Key = v
}

func (x *Location) HasOrigin() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Origin != nil
}

func (x *Location) HasPath() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Origin.(*location_Path)
	return ok
}

func (x *Location) HasSameContainer() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Origin.(*location_SameContainer)
	return ok
}

func (x *Location) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *Location) ClearOrigin() {
	x.xxx_hidden_Origin = nil
}

func (x *Location) ClearPath() {
	if _, ok := x.xxx_hidden_Origin.(*location_Path); ok {
		x.xxx_hidden_Origin = nil
	}
}

func (x *Location) ClearSameContainer() {
	if _, ok := x.xxx_hidden_Origin.(*location_SameContainer); ok {
		x.xxx_hidden_Origin = nil
	}
}

func (x *Location) ClearKey() {
	x.xxx_hidden_Key = nil
}

const Location_Origin_not_set_case case_Location_Origin = 0
const Location_Path_case case_Location_Origin = 1
const Location_SameContainer_case case_Location_Origin = 3

func (x *Location) WhichOrigin() case_Location_Origin {
	if x == nil {
		return Location_Origin_not_set_case
	}
	switch x.xxx_hidden_Origin.(type) {
	case *location_Path:
		return Location_Path_case
	case *location_SameContainer:
		return Location_SameContainer_case
	default:
		return Location_Origin_not_set_case
	}
}

type Location_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Where the source container is. Required: "the entry's own container" is an
	// explicit choice here, never an absence.

	// Fields of oneof xxx_hidden_Origin:
	// Relative to the enclosing `Delta`'s container, exactly like
	// `Entry.path`. Empty `segments` means that container itself.
	Path *Path
	// The container reached by `Entry.path`, i.e. where the targets live.
	SameContainer *SameContainer
	// -- end of xxx_hidden_Origin
	// The source position within that container. Required; an unset `key` is an
	// error, and a `key` that reaches nothing is an error (never skipped).
	Key *Key
}

func (b0 Location_builder) Build() *Location {
	m0 := &Location{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Path != nil {
		x.xxx_hidden_Origin = &location_Path{b.Path}
	}
	if b.SameContainer != nil {
		x.xxx_hidden_Origin = &location_SameContainer{b.SameContainer}
	}
	x.xxx_hidden_Key = b.Key
	return m0
}

type case_Location_Origin protoreflect.FieldNumber

func (x case_Location_Origin) String() string {
	md := file_patch_path_proto_msgTypes[7].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isLocation_Origin interface {
	isLocation_Origin()
}

type location_Path struct {
	// Relative to the enclosing `Delta`'s container, exactly like
	// `Entry.path`. Empty `segments` means that container itself.
	Path *Path `protobuf:"bytes,1,opt,name=path,oneof"`
}

type location_SameContainer struct {
	// The container reached by `Entry.path`, i.e. where the targets live.
	SameContainer *SameContainer `protobuf:"bytes,3,opt,name=same_container,json=sameContainer,oneof"`
}

func (*location_Path) isLocation_Origin() {}

func (*location_SameContainer) isLocation_Origin() {}

// SameContainer selects the container reached by `Entry.path`. It carries no
// data; it is a message so that it can gain options later.
type SameContainer struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SameContainer) Reset() {
	*x = SameContainer{}
	mi := &file_patch_path_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SameContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SameContainer) ProtoMessage() {}

func (x *SameContainer) ProtoReflect() protoreflect.Message {
	mi := &file_patch_path_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SameContainer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SameContainer_builder) Build() *SameContainer {
	m0 := &SameContainer{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_patch_path_proto protoreflect.FileDescriptor

const file_patch_path_proto_rawDesc = "" +
	"\n" +
	"\x10patch/path.proto\x12\x05patch\"u\n" +
	"\x03Key\x12$\n" +
	"\x05field\x18\x01 \x01(\v2\f.patch.FieldH\x00R\x05field\x12\x16\n" +
	"\x05index\x18\x02 \x01(\x12H\x00R\x05index\x12(\n" +
	"\amap_key\x18\x03 \x01(\v2\r.patch.MapKeyH\x00R\x06mapKeyB\x06\n" +
	"\x04kind\"P\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tjson_name\x18\x02 \x01(\tR\bjsonName\x12\x16\n" +
	"\x06number\x18\x03 \x01(\rR\x06number\"P\n" +
	"\x06MapKey\x12\x0e\n" +
	"\x01s\x18\x01 \x01(\tH\x00R\x01s\x12\x0e\n" +
	"\x01i\x18\x02 \x01(\x12H\x00R\x01i\x12\x0e\n" +
	"\x01u\x18\x03 \x01(\x04H\x00R\x01u\x12\x0e\n" +
	"\x01b\x18\x04 \x01(\bH\x00R\x01bB\x06\n" +
	"\x04kind\".\n" +
	"\x04Path\x12&\n" +
	"\bsegments\x18\x01 \x03(\v2\n" +
	".patch.KeyR\bsegments\"\x81\x01\n" +
	"\bSelector\x12\x1e\n" +
	"\x03key\x18\x01 \x01(\v2\n" +
	".patch.KeyH\x00R\x03key\x12$\n" +
	"\x05range\x18\x02 \x01(\v2\f.patch.RangeH\x00R\x05range\x12'\n" +
	"\x06append\x18\x03 \x01(\v2\r.patch.AppendH\x00R\x06appendB\x06\n" +
	"\x04kind\"/\n" +
	"\x05Range\x12\x14\n" +
	"\x05begin\x18\x01 \x01(\x12R\x05begin\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x12R\x03end\"\b\n" +
	"\x06Append\"\x94\x01\n" +
	"\bLocation\x12!\n" +
	"\x04path\x18\x01 \x01(\v2\v.patch.PathH\x00R\x04path\x12=\n" +
	"\x0esame_container\x18\x03 \x01(\v2\x14.patch.SameContainerH\x00R\rsameContainer\x12\x1c\n" +
	"\x03key\x18\x02 \x01(\v2\n" +
	".patch.KeyR\x03keyB\b\n" +
	"\x06origin\"\x0f\n" +
	"\rSameContainerB1Z*github.com/lesomnus/protobuf-patch/patchpb\x92\x03\x02\b\x01b\beditionsp\xe8\a"

var file_patch_path_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_patch_path_proto_goTypes = []any{
	(*Key)(nil),           // 0: patch.Key
	(*Field)(nil),         // 1: patch.Field
	(*MapKey)(nil),        // 2: patch.MapKey
	(*Path)(nil),          // 3: patch.Path
	(*Selector)(nil),      // 4: patch.Selector
	(*Range)(nil),         // 5: patch.Range
	(*Append)(nil),        // 6: patch.Append
	(*Location)(nil),      // 7: patch.Location
	(*SameContainer)(nil), // 8: patch.SameContainer
}
var file_patch_path_proto_depIdxs = []int32{
	1, // 0: patch.Key.field:type_name -> patch.Field
	2, // 1: patch.Key.map_key:type_name -> patch.MapKey
	0, // 2: patch.Path.segments:type_name -> patch.Key
	0, // 3: patch.Selector.key:type_name -> patch.Key
	5, // 4: patch.Selector.range:type_name -> patch.Range
	6, // 5: patch.Selector.append:type_name -> patch.Append
	3, // 6: patch.Location.path:type_name -> patch.Path
	8, // 7: patch.Location.same_container:type_name -> patch.SameContainer
	0, // 8: patch.Location.key:type_name -> patch.Key
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_patch_path_proto_init() }
func file_patch_path_proto_init() {
	if File_patch_path_proto != nil {
		return
	}
	file_patch_path_proto_msgTypes[0].OneofWrappers = []any{
		(*key_Field)(nil),
		(*key_Index)(nil),
		(*key_MapKey)(nil),
	}
	file_patch_path_proto_msgTypes[2].OneofWrappers = []any{
		(*mapKey_S)(nil),
		(*mapKey_I)(nil),
		(*mapKey_U)(nil),
		(*mapKey_B)(nil),
	}
	file_patch_path_proto_msgTypes[4].OneofWrappers = []any{
		(*selector_Key)(nil),
		(*selector_Range)(nil),
		(*selector_Append)(nil),
	}
	file_patch_path_proto_msgTypes[7].OneofWrappers = []any{
		(*location_Path)(nil),
		(*location_SameContainer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patch_path_proto_rawDesc), len(file_patch_path_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patch_path_proto_goTypes,
		DependencyIndexes: file_patch_path_proto_depIdxs,
		MessageInfos:      file_patch_path_proto_msgTypes,
	}.Build()
	File_patch_path_proto = out.File
	file_patch_path_proto_goTypes = nil
	file_patch_path_proto_depIdxs = nil
}
