// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: patch/value.proto

package patchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Value is a literal carried by `test`, `insert`, and `assign`.
//
// SELF-DESCRIBING. Each arm corresponds to exactly one protobuf type class, so
// a reader can validate a Value against a target field WITHOUT converting it,
// and a producer has exactly one legal arm for any given target. There is no
// conversion lattice: a Value whose arm does not match the target's kind is an
// error, never a widened, narrowed, or truncated write.
//
//	target field kind                   | arm
//	------------------------------------+-----
//	bool                                | b
//	int32, sint32, sfixed32             | i32
//	int64, sint64, sfixed64             | i64
//	uint32, fixed32                     | u32
//	uint64, fixed64                     | u64
//	float                               | f32
//	double                              | f64
//	string                              | s
//	bytes                               | x
//	enum                                | e
//	message                             | m
//	repeated (any element type)         | l
//	map (any key/value type)            | map
//
// Given a target field, the arm is uniquely determined, so a Value has exactly
// one legal encoding of any logical value and can be validated without
// conversion. This does NOT make a Delta canonical: `MessageValue.fields`,
// `MapValue.entries`, and `Targets.selectors` are order-insensitive
// collections stored in ordered `repeated` fields, so byte equality is
// strictly STRONGER than logical equality. Do not use proto equality on a
// `Patch` for deduplication or idempotency checks.
//
// There is deliberately NO null arm. "Absent" is not a value:
//   - to clear a field or delete an entry, use `remove`;
//   - to assert absence, use `test.exists = false`;
//   - a field absent from a `MessageValue` is simply not set.
//
// This removes the three-way overload of null (clear / absent / empty) and the
// second, redundant spelling of `remove`.
//
// An unset `kind` is an ERROR, not an implicit clear. So is an arm this reader
// does not recognize — see the forward-compatibility rules on `patch.Patch`.
type Value struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind isValue_Kind           `protobuf_oneof:"kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_patch_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_patch_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Value) GetB() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_B); ok {
			return x.B
		}
	}
	return false
}

func (x *Value) GetI32() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_I32); ok {
			return x.I32
		}
	}
	return 0
}

func (x *Value) GetI64() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_I64); ok {
			return x.I64
		}
	}
	return 0
}

func (x *Value) GetU32() uint32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_U32); ok {
			return x.U32
		}
	}
	return 0
}

func (x *Value) GetU64() uint64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_U64); ok {
			return x.U64
		}
	}
	return 0
}

func (x *Value) GetF32() float32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_F32); ok {
			return x.F32
		}
	}
	return 0
}

func (x *Value) GetF64() float64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_F64); ok {
			return x.F64
		}
	}
	return 0
}

func (x *Value) GetS() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_S); ok {
			return x.S
		}
	}
	return ""
}

func (x *Value) GetX() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_X); ok {
			return x.X
		}
	}
	return nil
}

func (x *Value) GetE() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_E); ok {
			return x.E
		}
	}
	return 0
}

func (x *Value) GetM() *MessageValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_M); ok {
			return x.M
		}
	}
	return nil
}

func (x *Value) GetL() *ListValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_L); ok {
			return x.L
		}
	}
	return nil
}

func (x *Value) GetMap() *MapValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_Map); ok {
			return x.Map
		}
	}
	return nil
}

func (x *Value) SetB(v bool) {
	x.xxx_hidden_Kind = &value_B{v}
}

func (x *Value) SetI32(v int32) {
	x.xxx_hidden_Kind = &value_I32{v}
}

func (x *Value) SetI64(v int64) {
	x.xxx_hidden_Kind = &value_I64{v}
}

func (x *Value) SetU32(v uint32) {
	x.xxx_hidden_Kind = &value_U32{v}
}

func (x *Value) SetU64(v uint64) {
	x.xxx_hidden_Kind = &value_U64{v}
}

func (x *Value) SetF32(v float32) {
	x.xxx_hidden_Kind = &value_F32{v}
}

func (x *Value) SetF64(v float64) {
	x.xxx_hidden_Kind = &value_F64{v}
}

func (x *Value) SetS(v string) {
	x.xxx_hidden_Kind = &value_S{v}
}

func (x *Value) SetX(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Kind = &value_X{v}
}

func (x *Value) SetE(v int32) {
	x.xxx_hidden_Kind = &value_E{v}
}

func (x *Value) SetM(v *MessageValue) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &value_M{v}
}

func (x *Value) SetL(v *ListValue) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &value_L{v}
}

func (x *Value) SetMap(v *MapValue) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &value_Map{v}
}

func (x *Value) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Value) HasB() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_B)
	return ok
}

func (x *Value) HasI32() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_I32)
	return ok
}

func (x *Value) HasI64() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_I64)
	return ok
}

func (x *Value) HasU32() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_U32)
	return ok
}

func (x *Value) HasU64() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_U64)
	return ok
}

func (x *Value) HasF32() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_F32)
	return ok
}

func (x *Value) HasF64() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_F64)
	return ok
}

func (x *Value) HasS() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_S)
	return ok
}

func (x *Value) HasX() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_X)
	return ok
}

func (x *Value) HasE() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_E)
	return ok
}

func (x *Value) HasM() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_M)
	return ok
}

func (x *Value) HasL() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_L)
	return ok
}

func (x *Value) HasMap() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_Map)
	return ok
}

func (x *Value) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Value) ClearB() {
	if _, ok := x.xxx_hidden_Kind.(*value_B); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearI32() {
	if _, ok := x.xxx_hidden_Kind.(*value_I32); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearI64() {
	if _, ok := x.xxx_hidden_Kind.(*value_I64); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearU32() {
	if _, ok := x.xxx_hidden_Kind.(*value_U32); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearU64() {
	if _, ok := x.xxx_hidden_Kind.(*value_U64); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearF32() {
	if _, ok := x.xxx_hidden_Kind.(*value_F32); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearF64() {
	if _, ok := x.xxx_hidden_Kind.(*value_F64); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearS() {
	if _, ok := x.xxx_hidden_Kind.(*value_S); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearX() {
	if _, ok := x.xxx_hidden_Kind.(*value_X); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearE() {
	if _, ok := x.xxx_hidden_Kind.(*value_E); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearM() {
	if _, ok := x.xxx_hidden_Kind.(*value_M); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearL() {
	if _, ok := x.xxx_hidden_Kind.(*value_L); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearMap() {
	if _, ok := x.xxx_hidden_Kind.(*value_Map); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Value_Kind_not_set_case case_Value_Kind = 0
const Value_B_case case_Value_Kind = 1
const Value_I32_case case_Value_Kind = 2
const Value_I64_case case_Value_Kind = 3
const Value_U32_case case_Value_Kind = 4
const Value_U64_case case_Value_Kind = 5
const Value_F32_case case_Value_Kind = 6
const Value_F64_case case_Value_Kind = 7
const Value_S_case case_Value_Kind = 8
const Value_X_case case_Value_Kind = 9
const Value_E_case case_Value_Kind = 10
const Value_M_case case_Value_Kind = 11
const Value_L_case case_Value_Kind = 12
const Value_Map_case case_Value_Kind = 13

func (x *Value) WhichKind() case_Value_Kind {
	if x == nil {
		return Value_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *value_B:
		return Value_B_case
	case *value_I32:
		return Value_I32_case
	case *value_I64:
		return Value_I64_case
	case *value_U32:
		return Value_U32_case
	case *value_U64:
		return Value_U64_case
	case *value_F32:
		return Value_F32_case
	case *value_F64:
		return Value_F64_case
	case *value_S:
		return Value_S_case
	case *value_X:
		return Value_X_case
	case *value_E:
		return Value_E_case
	case *value_M:
		return Value_M_case
	case *value_L:
		return Value_L_case
	case *value_Map:
		return Value_Map_case
	default:
		return Value_Kind_not_set_case
	}
}

type Value_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Kind:
	B   *bool
	I32 *int32
	I64 *int64
	U32 *uint32
	U64 *uint64
	F32 *float32
	F64 *float64
	S   *string
	X   []byte
	// Enum value number. Signed: enum numbers are int32 and may be negative.
	//
	// Against a CLOSED enum (`features.enum_type = CLOSED`), `e` MUST be a
	// number the target enum declares; an undeclared number is an error.
	// Against an OPEN enum any int32 is legal and is stored as written.
	E   *int32
	M   *MessageValue
	L   *ListValue
	Map *MapValue
	// -- end of xxx_hidden_Kind
}

func (b0 Value_builder) Build() *Value {
	m0 := &Value{}
	b, x := &b0, m0
	_, _ = b, x
	if b.B != nil {
		x.xxx_hidden_Kind = &value_B{*b.B}
	}
	if b.I32 != nil {
		x.xxx_hidden_Kind = &value_I32{*b.I32}
	}
	if b.I64 != nil {
		x.xxx_hidden_Kind = &value_I64{*b.I64}
	}
	if b.U32 != nil {
		x.xxx_hidden_Kind = &value_U32{*b.U32}
	}
	if b.U64 != nil {
		x.xxx_hidden_Kind = &value_U64{*b.U64}
	}
	if b.F32 != nil {
		x.xxx_hidden_Kind = &value_F32{*b.F32}
	}
	if b.F64 != nil {
		x.xxx_hidden_Kind = &value_F64{*b.F64}
	}
	if b.S != nil {
		x.xxx_hidden_Kind = &value_S{*b.S}
	}
	if b.X != nil {
		x.xxx_hidden_Kind = &value_X{b.X}
	}
	if b.E != nil {
		x.xxx_hidden_Kind = &value_E{*b.E}
	}
	if b.M != nil {
		x.xxx_hidden_Kind = &value_M{b.M}
	}
	if b.L != nil {
		x.xxx_hidden_Kind = &value_L{b.L}
	}
	if b.Map != nil {
		x.xxx_hidden_Kind = &value_Map{b.Map}
	}
	return m0
}

type case_Value_Kind protoreflect.FieldNumber

func (x case_Value_Kind) String() string {
	md := file_patch_value_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isValue_Kind interface {
	isValue_Kind()
}

type value_B struct {
	B bool `protobuf:"varint,1,opt,name=b,oneof"`
}

type value_I32 struct {
	I32 int32 `protobuf:"zigzag32,2,opt,name=i32,oneof"`
}

type value_I64 struct {
	I64 int64 `protobuf:"zigzag64,3,opt,name=i64,oneof"`
}

type value_U32 struct {
	U32 uint32 `protobuf:"varint,4,opt,name=u32,oneof"`
}

type value_U64 struct {
	U64 uint64 `protobuf:"varint,5,opt,name=u64,oneof"`
}

type value_F32 struct {
	F32 float32 `protobuf:"fixed32,6,opt,name=f32,oneof"`
}

type value_F64 struct {
	F64 float64 `protobuf:"fixed64,7,opt,name=f64,oneof"`
}

type value_S struct {
	S string `protobuf:"bytes,8,opt,name=s,oneof"`
}

type value_X struct {
	X []byte `protobuf:"bytes,9,opt,name=x,oneof"`
}

type value_E struct {
	// Enum value number. Signed: enum numbers are int32 and may be negative.
	//
	// Against a CLOSED enum (`features.enum_type = CLOSED`), `e` MUST be a
	// number the target enum declares; an undeclared number is an error.
	// Against an OPEN enum any int32 is legal and is stored as written.
	E int32 `protobuf:"zigzag32,10,opt,name=e,oneof"`
}

type value_M struct {
	M *MessageValue `protobuf:"bytes,11,opt,name=m,oneof"`
}

type value_L struct {
	L *ListValue `protobuf:"bytes,12,opt,name=l,oneof"`
}

type value_Map struct {
	Map *MapValue `protobuf:"bytes,13,opt,name=map,oneof"`
}

func (*value_B) isValue_Kind() {}

func (*value_I32) isValue_Kind() {}

func (*value_I64) isValue_Kind() {}

func (*value_U32) isValue_Kind() {}

func (*value_U64) isValue_Kind() {}

func (*value_F32) isValue_Kind() {}

func (*value_F64) isValue_Kind() {}

func (*value_S) isValue_Kind() {}

func (*value_X) isValue_Kind() {}

func (*value_E) isValue_Kind() {}

func (*value_M) isValue_Kind() {}

func (*value_L) isValue_Kind() {}

func (*value_Map) isValue_Kind() {}

// MessageValue is the contents of a message, keyed by field.
//
// Distinct from MapValue so that a Value says for itself whether it is a
// message or a map, rather than requiring the target descriptor to decide.
//
// `fields` keys MUST be unique after resolution; a repeated key is an error.
//
// At most one member of any single `oneof` OF THE TARGET MESSAGE may appear in
// `fields`. Two members of one target oneof are an error even though their
// keys differ, because setting one clears the other.
//
// `fields` is applied as an UNORDERED mapping: no application order is
// defined, and no two entries may interact.
//
// A field absent from `fields` is NOT SET (for `assign` at container scope,
// which replaces wholesale) or LEFT UNTOUCHED (for `insert` at container
// scope) — see the per-operation table on `patch.Entry`.
type MessageValue struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Fields *[]*FieldValue         `protobuf:"bytes,1,rep,name=fields"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MessageValue) Reset() {
	*x = MessageValue{}
	mi := &file_patch_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageValue) ProtoMessage() {}

func (x *MessageValue) ProtoReflect() protoreflect.Message {
	mi := &file_patch_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MessageValue) GetFields() []*FieldValue {
	if x != nil {
		if x.xxx_hidden_Fields != nil {
			return *x.xxx_hidden_Fields
		}
	}
	return nil
}

func (x *MessageValue) SetFields(v []*FieldValue) {
	x.xxx_hidden_Fields = &v
}

type MessageValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Fields []*FieldValue
}

func (b0 MessageValue_builder) Build() *MessageValue {
	m0 := &MessageValue{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Fields = &b.Fields
	return m0
}

type FieldValue struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   *Field                 `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value *Value                 `protobuf:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_patch_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_patch_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FieldValue) GetKey() *Field {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *FieldValue) GetValue() *Value {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *FieldValue) SetKey(v *Field) {
	x.xxx_hidden_Key = v
}

func (x *FieldValue) SetValue(v *Value) {
	x.xxx_hidden_Value = v
}

func (x *FieldValue) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *FieldValue) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *FieldValue) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *FieldValue) ClearValue() {
	x.xxx_hidden_Value = nil
}

type FieldValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. An unset key is an error.
	Key *Field
	// Required. An unset value is an error — use `remove` to clear a field.
	Value *Value
}

func (b0 FieldValue_builder) Build() *FieldValue {
	m0 := &FieldValue{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

// ListValue is the contents of a repeated field, in order.
//
// Every element must be present and must match the repeated field's element
// kind. There is no null element, so the encoded length always equals the
// decoded length.
type ListValue struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Values *[]*Value              `protobuf:"bytes,1,rep,name=values"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_patch_value_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_patch_value_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		if x.xxx_hidden_Values != nil {
			return *x.xxx_hidden_Values
		}
	}
	return nil
}

func (x *ListValue) SetValues(v []*Value) {
	x.xxx_hidden_Values = &v
}

type ListValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Values []*Value
}

func (b0 ListValue_builder) Build() *ListValue {
	m0 := &ListValue{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Values = &b.Values
	return m0
}

// MapValue is the contents of a map field.
//
// `entries` keys MUST be unique after resolution; a repeated key is an error.
// `entries` is applied as an unordered mapping.
type MapValue struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*MapEntry           `protobuf:"bytes,1,rep,name=entries"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_patch_value_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_patch_value_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MapValue) GetEntries() []*MapEntry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *MapValue) SetEntries(v []*MapEntry) {
	x.xxx_hidden_Entries = &v
}

type MapValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries []*MapEntry
}

func (b0 MapValue_builder) Build() *MapValue {
	m0 := &MapValue{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

type MapEntry struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   *MapKey                `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value *Value                 `protobuf:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MapEntry) Reset() {
	*x = MapEntry{}
	mi := &file_patch_value_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEntry) ProtoMessage() {}

func (x *MapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_patch_value_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MapEntry) GetKey() *MapKey {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *MapEntry) GetValue() *Value {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *MapEntry) SetKey(v *MapKey) {
	x.xxx_hidden_Key = v
}

func (x *MapEntry) SetValue(v *Value) {
	x.xxx_hidden_Value = v
}

func (x *MapEntry) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *MapEntry) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *MapEntry) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *MapEntry) ClearValue() {
	x.xxx_hidden_Value = nil
}

type MapEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required, and must match the map's declared key type. An unset key is an
	// error.
	Key *MapKey
	// Required. An unset value is an error — protobuf maps cannot hold absent
	// values; use `remove` to delete an entry.
	Value *Value
}

func (b0 MapEntry_builder) Build() *MapEntry {
	m0 := &MapEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

var File_patch_value_proto protoreflect.FileDescriptor

const file_patch_value_proto_rawDesc = "" +
	"\n" +
	"\x11patch/value.proto\x12\x05patch\x1a\x10patch/path.proto\"\xb9\x02\n" +
	"\x05Value\x12\x0e\n" +
	"\x01b\x18\x01 \x01(\bH\x00R\x01b\x12\x12\n" +
	"\x03i32\x18\x02 \x01(\x11H\x00R\x03i32\x12\x12\n" +
	"\x03i64\x18\x03 \x01(\x12H\x00R\x03i64\x12\x12\n" +
	"\x03u32\x18\x04 \x01(\rH\x00R\x03u32\x12\x12\n" +
	"\x03u64\x18\x05 \x01(\x04H\x00R\x03u64\x12\x12\n" +
	"\x03f32\x18\x06 \x01(\x02H\x00R\x03f32\x12\x12\n" +
	"\x03f64\x18\a \x01(\x01H\x00R\x03f64\x12\x0e\n" +
	"\x01s\x18\b \x01(\tH\x00R\x01s\x12\x0e\n" +
	"\x01x\x18\t \x01(\fH\x00R\x01x\x12\x0e\n" +
	"\x01e\x18\n" +
	" \x01(\x11H\x00R\x01e\x12#\n" +
	"\x01m\x18\v \x01(\v2\x13.patch.MessageValueH\x00R\x01m\x12 \n" +
	"\x01l\x18\f \x01(\v2\x10.patch.ListValueH\x00R\x01l\x12#\n" +
	"\x03map\x18\r \x01(\v2\x0f.patch.MapValueH\x00R\x03mapB\x06\n" +
	"\x04kindJ\x04\b\x0e\x10\x10\"9\n" +
	"\fMessageValue\x12)\n" +
	"\x06fields\x18\x01 \x03(\v2\x11.patch.FieldValueR\x06fields\"P\n" +
	"\n" +
	"FieldValue\x12\x1e\n" +
	"\x03key\x18\x01 \x01(\v2\f.patch.FieldR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.patch.ValueR\x05value\"1\n" +
	"\tListValue\x12$\n" +
	"\x06values\x18\x01 \x03(\v2\f.patch.ValueR\x06values\"5\n" +
	"\bMapValue\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.patch.MapEntryR\aentries\"O\n" +
	"\bMapEntry\x12\x1f\n" +
	"\x03key\x18\x01 \x01(\v2\r.patch.MapKeyR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.patch.ValueR\x05valueB1Z*github.com/lesomnus/protobuf-patch/patchpb\x92\x03\x02\b\x01b\beditionsp\xe8\a"

var file_patch_value_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_patch_value_proto_goTypes = []any{
	(*Value)(nil),        // 0: patch.Value
	(*MessageValue)(nil), // 1: patch.MessageValue
	(*FieldValue)(nil),   // 2: patch.FieldValue
	(*ListValue)(nil),    // 3: patch.ListValue
	(*MapValue)(nil),     // 4: patch.MapValue
	(*MapEntry)(nil),     // 5: patch.MapEntry
	(*Field)(nil),        // 6: patch.Field
	(*MapKey)(nil),       // 7: patch.MapKey
}
var file_patch_value_proto_depIdxs = []int32{
	1,  // 0: patch.Value.m:type_name -> patch.MessageValue
	3,  // 1: patch.Value.l:type_name -> patch.ListValue
	4,  // 2: patch.Value.map:type_name -> patch.MapValue
	2,  // 3: patch.MessageValue.fields:type_name -> patch.FieldValue
	6,  // 4: patch.FieldValue.key:type_name -> patch.Field
	0,  // 5: patch.FieldValue.value:type_name -> patch.Value
	0,  // 6: patch.ListValue.values:type_name -> patch.Value
	5,  // 7: patch.MapValue.entries:type_name -> patch.MapEntry
	7,  // 8: patch.MapEntry.key:type_name -> patch.MapKey
	0,  // 9: patch.MapEntry.value:type_name -> patch.Value
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_patch_value_proto_init() }
func file_patch_value_proto_init() {
	if File_patch_value_proto != nil {
		return
	}
	file_patch_path_proto_init()
	file_patch_value_proto_msgTypes[0].OneofWrappers = []any{
		(*value_B)(nil),
		(*value_I32)(nil),
		(*value_I64)(nil),
		(*value_U32)(nil),
		(*value_U64)(nil),
		(*value_F32)(nil),
		(*value_F64)(nil),
		(*value_S)(nil),
		(*value_X)(nil),
		(*value_E)(nil),
		(*value_M)(nil),
		(*value_L)(nil),
		(*value_Map)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patch_value_proto_rawDesc), len(file_patch_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patch_value_proto_goTypes,
		DependencyIndexes: file_patch_value_proto_depIdxs,
		MessageInfos:      file_patch_value_proto_msgTypes,
	}.Build()
	File_patch_value_proto = out.File
	file_patch_value_proto_goTypes = nil
	file_patch_value_proto_depIdxs = nil
}
