// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conformance/case.proto

package conformancepb

import (
	sample "github.com/lesomnus/protobuf-patch/internal/sample"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Suite is a file of conformance cases.
//
// The corpus is DATA, not Go code, so that every implementation of the patch
// format can run the same cases without importing another implementation's
// tests. Applying a Patch to a live message and applying one to serialized
// bytes are necessarily separate engines; this is what keeps them from
// drifting into reading the same document differently, which is exactly what
// happened to the three backends of the previous design.
type Suite struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cases *[]*Case               `protobuf:"bytes,1,rep,name=cases"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Suite) Reset() {
	*x = Suite{}
	mi := &file_conformance_case_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suite) ProtoMessage() {}

func (x *Suite) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_case_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Suite) GetCases() []*Case {
	if x != nil {
		if x.xxx_hidden_Cases != nil {
			return *x.xxx_hidden_Cases
		}
	}
	return nil
}

func (x *Suite) SetCases(v []*Case) {
	x.xxx_hidden_Cases = &v
}

type Suite_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cases []*Case
}

func (b0 Suite_builder) Build() *Suite {
	m0 := &Suite{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cases = &b.Cases
	return m0
}

// Case is one document applied to one input, with the single outcome every
// conforming implementation must produce.
type Case struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Doc         *string                `protobuf:"bytes,2,opt,name=doc"`
	xxx_hidden_Patch       *patchpb.Patch         `protobuf:"bytes,3,opt,name=patch"`
	xxx_hidden_Input       *sample.Value          `protobuf:"bytes,4,opt,name=input"`
	xxx_hidden_Want        isCase_Want            `protobuf_oneof:"want"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Case) Reset() {
	*x = Case{}
	mi := &file_conformance_case_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_case_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Case) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Case) GetDoc() string {
	if x != nil {
		if x.xxx_hidden_Doc != nil {
			return *x.xxx_hidden_Doc
		}
		return ""
	}
	return ""
}

func (x *Case) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *Case) GetInput() *sample.Value {
	if x != nil {
		return x.xxx_hidden_Input
	}
	return nil
}

func (x *Case) GetOutput() *sample.Value {
	if x != nil {
		if x, ok := x.xxx_hidden_Want.(*case_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *Case) GetError() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Want.(*case_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *Case) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Case) SetDoc(v string) {
	x.xxx_hidden_Doc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Case) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *Case) SetInput(v *sample.Value) {
	x.xxx_hidden_Input = v
}

func (x *Case) SetOutput(v *sample.Value) {
	if v == nil {
		x.xxx_hidden_Want = nil
		return
	}
	x.xxx_hidden_Want = &case_Output{v}
}

func (x *Case) SetError(v string) {
	x.xxx_hidden_Want = &case_Error{v}
}

func (x *Case) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Case) HasDoc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Case) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *Case) HasInput() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Input != nil
}

func (x *Case) HasWant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Want != nil
}

func (x *Case) HasOutput() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Want.(*case_Output)
	return ok
}

func (x *Case) HasError() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Want.(*case_Error)
	return ok
}

func (x *Case) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Case) ClearDoc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Doc = nil
}

func (x *Case) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

func (x *Case) ClearInput() {
	x.xxx_hidden_Input = nil
}

func (x *Case) ClearWant() {
	x.xxx_hidden_Want = nil
}

func (x *Case) ClearOutput() {
	if _, ok := x.xxx_hidden_Want.(*case_Output); ok {
		x.xxx_hidden_Want = nil
	}
}

func (x *Case) ClearError() {
	if _, ok := x.xxx_hidden_Want.(*case_Error); ok {
		x.xxx_hidden_Want = nil
	}
}

const Case_Want_not_set_case case_Case_Want = 0
const Case_Output_case case_Case_Want = 5
const Case_Error_case case_Case_Want = 6

func (x *Case) WhichWant() case_Case_Want {
	if x == nil {
		return Case_Want_not_set_case
	}
	switch x.xxx_hidden_Want.(type) {
	case *case_Output:
		return Case_Output_case
	case *case_Error:
		return Case_Error_case
	default:
		return Case_Want_not_set_case
	}
}

type Case_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Short identifier, unique within the corpus.
	Name *string
	// Why this case exists — the rule it pins, in one line.
	Doc *string
	// The document under test.
	Patch *patchpb.Patch
	// The message it is applied to.
	Input *sample.Value
	// Exactly one is required.

	// Fields of oneof xxx_hidden_Want:
	// The message the implementation must produce.
	Output *sample.Value
	// The name of the patch.Code the implementation must report, as
	// patch.Code.String writes it. On failure the input must also be left
	// unchanged: the format applies entirely or not at all.
	Error *string
	// -- end of xxx_hidden_Want
}

func (b0 Case_builder) Build() *Case {
	m0 := &Case{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Doc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Doc = b.Doc
	}
	x.xxx_hidden_Patch = b.Patch
	x.xxx_hidden_Input = b.Input
	if b.Output != nil {
		x.xxx_hidden_Want = &case_Output{b.Output}
	}
	if b.Error != nil {
		x.xxx_hidden_Want = &case_Error{*b.Error}
	}
	return m0
}

type case_Case_Want protoreflect.FieldNumber

func (x case_Case_Want) String() string {
	md := file_conformance_case_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isCase_Want interface {
	isCase_Want()
}

type case_Output struct {
	// The message the implementation must produce.
	Output *sample.Value `protobuf:"bytes,5,opt,name=output,oneof"`
}

type case_Error struct {
	// The name of the patch.Code the implementation must report, as
	// patch.Code.String writes it. On failure the input must also be left
	// unchanged: the format applies entirely or not at all.
	Error string `protobuf:"bytes,6,opt,name=error,oneof"`
}

func (*case_Output) isCase_Want() {}

func (*case_Error) isCase_Want() {}

var File_conformance_case_proto protoreflect.FileDescriptor

const file_conformance_case_proto_rawDesc = "" +
	"\n" +
	"\x16conformance/case.proto\x12\vconformance\x1a\x11patch/patch.proto\x1a\x12sample/value.proto\"0\n" +
	"\x05Suite\x12'\n" +
	"\x05cases\x18\x01 \x03(\v2\x11.conformance.CaseR\x05cases\"\xbe\x01\n" +
	"\x04Case\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03doc\x18\x02 \x01(\tR\x03doc\x12\"\n" +
	"\x05patch\x18\x03 \x01(\v2\f.patch.PatchR\x05patch\x12#\n" +
	"\x05input\x18\x04 \x01(\v2\r.sample.ValueR\x05input\x12'\n" +
	"\x06output\x18\x05 \x01(\v2\r.sample.ValueH\x00R\x06output\x12\x16\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05errorB\x06\n" +
	"\x04wantBCZ<github.com/lesomnus/protobuf-patch/conformance/conformancepb\x92\x03\x02\b\x01b\beditionsp\xe8\a"

var file_conformance_case_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_conformance_case_proto_goTypes = []any{
	(*Suite)(nil),         // 0: conformance.Suite
	(*Case)(nil),          // 1: conformance.Case
	(*patchpb.Patch)(nil), // 2: patch.Patch
	(*sample.Value)(nil),  // 3: sample.Value
}
var file_conformance_case_proto_depIdxs = []int32{
	1, // 0: conformance.Suite.cases:type_name -> conformance.Case
	2, // 1: conformance.Case.patch:type_name -> patch.Patch
	3, // 2: conformance.Case.input:type_name -> sample.Value
	3, // 3: conformance.Case.output:type_name -> sample.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_conformance_case_proto_init() }
func file_conformance_case_proto_init() {
	if File_conformance_case_proto != nil {
		return
	}
	file_conformance_case_proto_msgTypes[1].OneofWrappers = []any{
		(*case_Output)(nil),
		(*case_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conformance_case_proto_rawDesc), len(file_conformance_case_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conformance_case_proto_goTypes,
		DependencyIndexes: file_conformance_case_proto_depIdxs,
		MessageInfos:      file_conformance_case_proto_msgTypes,
	}.Build()
	File_conformance_case_proto = out.File
	file_conformance_case_proto_goTypes = nil
	file_conformance_case_proto_depIdxs = nil
}
